import type { StockSpec } from '../types.ts';

// Colors sampled from photos and the operators' paint codes (S-Bahn red is NCS S 1580-R).
const ROOF = '#8C8C8C';
const GLASS = '#1E2226';
const BLACK = '#161718';

type Livery = Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'windowColor' | 'skirt' | 'stripes' | 'frontStripes' | 'pantograph'>;

/** Older U-Bahn cars: plain BVG yellow, face included, with a black skirt. */
const classicYellow = (body: string): Livery => ({
  body,
  finish: 'paint',
  roof: ROOF,
  front: body,
  doorColor: body,
  windowColor: GLASS,
  skirt: '#1E1E22',
  pantograph: false,
});

/** Newer U-Bahn trains: yellow with a black mask around the cab windows. */
const maskedYellow = (body: string, skirt: string): Livery => ({
  body,
  finish: 'paint',
  roof: ROOF,
  front: BLACK,
  doorColor: body,
  windowColor: GLASS,
  skirt,
  frontStripes: [{ color: body, from: 0, to: 0.3 }],
  pantograph: false,
});

/** S-Bahn Berlin: red below the windows, ocher above (the classic 1920s colors, chosen again by a 1997 poll). */
const sbahn = (red: string, ocher: string, doors: string): Livery => ({
  body: red,
  finish: 'paint',
  roof: '#9A9C9E',
  front: red,
  doorColor: doors,
  windowColor: GLASS,
  skirt: '#4E5754',
  stripes: [
    { color: ocher, from: 0.52, to: 1 },
    { color: GLASS, from: 0.56, to: 0.84 },
  ],
  frontStripes: [
    { color: ocher, from: 0.52, to: 1 },
    { color: GLASS, from: 0.56, to: 0.86 },
  ],
  pantograph: false,
});

/** BVG trams: yellow with a dark window band and gray skirt. */
const tramLivery: Livery = {
  body: '#F4C300',
  finish: 'paint',
  roof: '#D8D8D4',
  front: '#F4C300',
  doorColor: '#F4C300',
  windowColor: GLASS,
  skirt: '#6E7072',
  stripes: [{ color: '#2B2B2B', from: 0.4, to: 0.86 }],
  frontStripes: [{ color: '#2B2B2B', from: 0.45, to: 0.9 }],
  pantograph: true,
};

export const stock: StockSpec[] = [
  // U-Bahn small profile (U1–U4): 2.30 m wide cars
  {
    id: 'berlin-a3e',
    name: 'A3E',
    maker: 'O&K, rebuilt by BVG',
    introduced: 1964,
    blurb: 'Germany’s oldest subway cars in daily service: built in the 1960s, some have run more than 3.7 million km.',
    length: 12.83,
    width: 2.3,
    height: 3.18,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...classicYellow('#F2B200'),
  },
  {
    id: 'berlin-gi1e',
    name: 'GI/1E',
    maker: 'LEW Hennigsdorf',
    introduced: 1978,
    blurb: 'East Germany’s only small-profile U-Bahn train, nicknamed Gisela. Sixty of her sisters were sold to the Pyongyang Metro.',
    length: 12.83,
    width: 2.26,
    height: 3.19,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...classicYellow('#F2B200'),
  },
  {
    id: 'berlin-a3l92',
    name: 'A3L92',
    maker: 'ABB Henschel / AEG',
    introduced: 1993,
    blurb: 'Rushed into service after reunification, when the reopened small-profile network suddenly needed more trains.',
    length: 12.83,
    width: 2.3,
    height: 3.18,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...classicYellow('#F2B200'),
  },
  {
    id: 'berlin-hk',
    name: 'HK',
    maker: 'Adtranz / Bombardier',
    introduced: 2001,
    blurb: 'The H’s little sister, 35 cm narrower for the old tunnels: four cars you can walk straight through.',
    length: 12.9,
    width: 2.3,
    height: 3.2,
    doors: 3,
    profile: 'box',
    nose: 'rounded',
    ...maskedYellow('#F2C200', '#85858A'),
  },
  {
    id: 'berlin-ik',
    name: 'IK',
    maker: 'Stadler',
    introduced: 2015,
    blurb: 'Built for the narrow lines, some IKs have also worked the wide U5, with boards along their sides to bridge the gap.',
    length: 12.91,
    width: 2.4,
    height: 3.21,
    doors: 3,
    profile: 'rounded',
    nose: 'rounded',
    ...maskedYellow('#F2C200', '#37393F'),
  },
  {
    id: 'berlin-jk',
    name: 'JK',
    maker: 'Stadler',
    introduced: 2025,
    blurb: 'Built in Berlin-Pankow, the JK carried its first passengers on U2 on 8 September 2025.',
    length: 12.91,
    width: 2.4,
    height: 3.16,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    ...maskedYellow('#F4C300', '#9A988C'),
  },
  // U-Bahn large profile (U5–U9): 2.65 m wide cars
  {
    id: 'berlin-f74',
    name: 'F74E / F76E',
    maker: 'O&K / Waggon Union',
    introduced: 1974,
    blurb: 'Rebuilt 2011–18 to reach their sixth decade; F74s once ran semi-automatically on U9 under automatic train control.',
    length: 16.05,
    width: 2.65,
    height: 3.43,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...classicYellow('#EBA300'),
    skirt: '#2E2E2E',
  },
  {
    id: 'berlin-f90',
    name: 'F84–F92',
    maker: 'Waggon Union / AEG / ABB',
    introduced: 1984,
    blurb: 'Four batches, F84 to F92, make these two-car units the workhorses of U6 and U7.',
    length: 16.05,
    width: 2.64,
    height: 3.42,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...classicYellow('#F0AE00'),
    frontStripes: [{ color: BLACK, from: 0.5, to: 0.86 }],
  },
  {
    id: 'berlin-h',
    name: 'H series',
    maker: 'ABB Henschel / Adtranz / Bombardier',
    introduced: 1996,
    blurb: 'Berlin’s first U-Bahn you can walk through end to end: six cars, one 98.7 m long room, first run on U6 in 1996.',
    length: 16.46,
    width: 2.65,
    height: 3.4,
    doors: 3,
    profile: 'box',
    nose: 'rounded',
    ...maskedYellow('#F2C200', '#37393F'),
  },
  {
    id: 'berlin-j',
    name: 'J',
    maker: 'Stadler',
    introduced: 2026,
    blurb: 'The first new trains for U5–U9 in over 30 years entered service on U5 in spring 2026; hundreds more are on order.',
    length: 16.05,
    width: 2.65,
    height: 3.43,
    doors: 3,
    profile: 'rounded',
    nose: 'slant',
    ...maskedYellow('#F4C300', '#3C4048'),
  },
  // S-Bahn: two-car units (36.8 m), coupled into trains of 4, 6 or 8 cars
  {
    id: 'berlin-480',
    name: 'BR 480',
    maker: 'AEG / Siemens / Waggon Union',
    introduced: 1987,
    blurb: 'Designed for West Berlin’s BVG, which ran the S-Bahn there from 1984; its last units now work only line S3.',
    length: 18.4,
    width: 3.12,
    height: 3.6,
    doors: 3,
    profile: 'box',
    nose: 'rounded',
    ...sbahn('#8B1E2B', '#C9A45C', '#8B1E2B'),
    roof: '#7F8285',
  },
  {
    id: 'berlin-481',
    name: 'BR 481/482',
    maker: 'AEG / Adtranz / Bombardier',
    introduced: 1996,
    blurb: '500 two-car units, the backbone of the S-Bahn: a wheel fracture in 2009 set off Berlin’s great S-Bahn crisis.',
    length: 18.4,
    width: 3.14,
    height: 3.59,
    doors: 3,
    profile: 'box',
    nose: 'rounded',
    ...sbahn('#B3202C', '#D8BC78', '#0A0A0A'),
  },
  {
    id: 'berlin-483',
    name: 'BR 483/484',
    maker: 'Stadler / Siemens',
    introduced: 2021,
    blurb: 'The S-Bahn’s boss likened its flat black face to a “speeding iPad”; fans call it the light switch.',
    length: 18.4,
    width: 3.14,
    height: 3.6,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...sbahn('#B3202C', '#D8BC78', '#0A0A0A'),
    front: '#0A0A0A',
    frontStripes: [
      { color: '#B3202C', from: 0, to: 0.3 },
      { color: '#D8BC78', from: 0.3, to: 0.34 },
    ],
  },
  // Trams
  {
    id: 'berlin-flexity',
    name: 'Flexity Berlin (long)',
    maker: 'Bombardier',
    introduced: 2011,
    blurb: 'Seven sections and 40 m of 100% low floor: nearly 200 long Flexitys carry Berlin’s busiest tram lines.',
    length: 40,
    width: 2.4,
    height: 3.45,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    ...tramLivery,
    sections: 7,
  },
  {
    id: 'berlin-flexity-short',
    name: 'Flexity Berlin (short)',
    maker: 'Bombardier',
    introduced: 2011,
    blurb: 'The 30.8 m, five-section Flexity: the same tram as the long one, two sections shorter.',
    length: 30.8,
    width: 2.4,
    height: 3.45,
    doors: 3,
    profile: 'tram',
    nose: 'rounded',
    ...tramLivery,
    sections: 5,
  },
  {
    id: 'berlin-gt6n',
    name: 'GT6N',
    maker: 'AEG / Adtranz',
    introduced: 1994,
    blurb: 'Berlin’s first low-floor trams arrived in 1994; at 2.30 m wide they still rule the narrow tracks of Köpenick.',
    length: 26.8,
    width: 2.3,
    height: 3.29,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    ...tramLivery,
    sections: 3,
  },
  {
    id: 'berlin-urbanliner',
    name: 'Urbanliner',
    maker: 'Alstom',
    introduced: 2026,
    blurb: 'At 51 m and nine sections, Berlin’s longest tram: the first carried passengers on M4 on 8 July 2026.',
    length: 50.98,
    width: 2.4,
    height: 3.5,
    doors: 5,
    profile: 'tram',
    nose: 'slant',
    ...tramLivery,
    sections: 9,
  },
];
