import type { StockSpec, StockStripe } from '../types.ts';

// Helsinki rolling stock in service, fall 2026. Dimensions are per car (per whole vehicle for trams). Metro trains
// are four cars at most since the Länsimetro stations were built short. City trams keep the green-and-yellow
// livery; the light rail Artic X54s are white. Colors are estimates from photos.

const GLASS = '#1C2227';
const METRO = '#EC4A26';
const TRAM_GREEN = '#1F8A47';
const TRAM_YELLOW = '#E3C64A';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

type Livery = Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'windowColor' | 'skirt' | 'stripes' | 'frontStripes' | 'pantograph'>;

/** Metro orange, dark skirt. */
const metro = (stripes: StockStripe[], frontStripes: StockStripe[]): Livery => ({
  body: METRO,
  finish: 'paint',
  roof: '#A3A8AC',
  front: METRO,
  doorColor: METRO,
  windowColor: GLASS,
  skirt: '#3A3F44',
  stripes,
  frontStripes,
  pantograph: false,
});

export const stock: StockSpec[] = [
  {
    id: 'helsinki-m100',
    name: 'M100',
    maker: 'Strömberg / Valmet',
    introduced: 1982,
    blurb: 'The world’s first metro trains with inverter-fed AC motors, developed by Finland’s Strömberg.',
    length: 22.1,
    width: 3.2,
    height: 3.7,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...metro([band('#3A3F44', 0.1, 0.2)], [band(GLASS, 0.52, 0.92)]),
  },
  {
    id: 'helsinki-m200',
    name: 'M200',
    maker: 'Bombardier / Alstom',
    introduced: 2001,
    blurb: 'Only twelve pairs were built, based on the Berlin S-Bahn’s Class 481, and they could take a pantograph if ever needed.',
    length: 22.1,
    width: 3.2,
    height: 3.7,
    doors: 3,
    profile: 'rounded',
    nose: 'rounded',
    ...metro([], [band('#1E2226', 0.26, 0.4), band(GLASS, 0.5, 0.92)]),
  },
  {
    id: 'helsinki-m300',
    name: 'M300',
    maker: 'CAF',
    introduced: 2016,
    blurb: 'Built to run without drivers, the M300s still carry their “temporary” cabs: the automation was called off in 2015.',
    length: 22.5,
    width: 3.2,
    height: 3.7,
    doors: 3,
    profile: 'rounded',
    nose: 'rounded',
    ...metro([band('#2C3136', 0.08, 0.2), band('#F4F4F2', 0.95, 0.97)], [band('#1B1F23', 0.26, 0.94)]),
  },
  {
    id: 'helsinki-sm5',
    name: 'Sm5 (FLIRT)',
    maker: 'Stadler',
    introduced: 2009,
    blurb: 'Built with 50–100% thicker insulation for Finnish winters, and shipped from Switzerland by road and ferry on account of their broad gauge.',
    length: 18.8,
    width: 3.2,
    height: 4.2,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    body: '#E5E7E9',
    finish: 'paint',
    roof: '#A8AEB3',
    front: '#E5E7E9',
    doorColor: '#C9CDD1',
    windowColor: GLASS,
    skirt: '#3E4348',
    stripes: [band('#8C4799', 0.35, 0.43), band('#2A2E33', 0.43, 0.84), band('#8C4799', 0.84, 0.92)],
    frontStripes: [band('#D8262E', 0.22, 0.3), band('#8C4799', 0.42, 0.48), band(GLASS, 0.5, 0.9)],
    pantograph: true,
  },
  {
    id: 'helsinki-sm4',
    name: 'Sm4',
    maker: 'CAF',
    introduced: 1999,
    blurb: 'Built by CAF to a Fiat Ferroviaria design and nicknamed “pupu”, the bunny. Up to five units can run coupled.',
    length: 27.1,
    width: 3.2,
    height: 4.3,
    doors: 2,
    profile: 'rounded',
    nose: 'flat',
    body: '#F1F2F0',
    finish: 'paint',
    roof: '#B4B9BD',
    front: '#F1F2F0',
    doorColor: '#6CB33F',
    windowColor: GLASS,
    skirt: '#8A9095',
    stripes: [band('#6CB33F', 0.28, 0.36)],
    frontStripes: [band('#6CB33F', 0.28, 0.36), band(GLASS, 0.52, 0.9)],
    pantograph: true,
  },
  {
    id: 'helsinki-artic',
    name: 'Artic',
    maker: 'Škoda Transtech',
    introduced: 2013,
    blurb: 'Designed with freely turning bogies to cope with Helsinki’s tight old curves, where the Variotram had failed.',
    length: 27.3,
    width: 2.4,
    height: 3.6,
    doors: 1,
    profile: 'tram',
    nose: 'rounded',
    body: TRAM_GREEN,
    finish: 'paint',
    roof: '#B9BEC2',
    front: TRAM_GREEN,
    doorColor: TRAM_GREEN,
    windowColor: GLASS,
    skirt: '#17663A',
    stripes: [band(TRAM_YELLOW, 0.4, 0.44), band('#1E2327', 0.44, 0.92)],
    frontStripes: [band(TRAM_YELLOW, 0.4, 0.44), band(GLASS, 0.44, 0.94)],
    pantograph: true,
    sections: 3,
  },
  {
    id: 'helsinki-mlnrv',
    name: 'MLNRV (Nr I/II)',
    maker: 'Valmet, rebuilt by HKL',
    introduced: 1973,
    blurb: 'High-floor Valmet trams from the 1970s–80s, lengthened with a 6.5 m low-floor middle section to live on until 2030.',
    length: 26.5,
    width: 2.3,
    height: 3.7,
    doors: 1,
    profile: 'tram',
    nose: 'flat',
    body: TRAM_GREEN,
    finish: 'paint',
    roof: '#9EA4A8',
    front: TRAM_GREEN,
    doorColor: '#B7BFC2',
    windowColor: GLASS,
    skirt: '#17663A',
    stripes: [band(TRAM_YELLOW, 0.5, 1)],
    frontStripes: [band(TRAM_YELLOW, 0.72, 1), band(GLASS, 0.46, 0.88)],
    pantograph: true,
    sections: 3,
  },
  {
    id: 'helsinki-artic-x54',
    name: 'Artic X54',
    maker: 'Škoda Transtech',
    introduced: 2021,
    blurb: 'Five modules and 34.5 m, with cabs at both ends. Built to grow to 44 m when the light rail lines need more room.',
    length: 34.5,
    width: 2.4,
    height: 3.6,
    doors: 1,
    profile: 'tram',
    nose: 'rounded',
    body: '#EDEFEF',
    finish: 'paint',
    roof: '#9FA6AB',
    front: '#EDEFEF',
    doorColor: '#EDEFEF',
    windowColor: GLASS,
    skirt: '#7D868C',
    stripes: [band('#2E3439', 0.42, 0.92)],
    frontStripes: [band('#7D868C', 0.18, 0.28), band(GLASS, 0.44, 0.94)],
    pantograph: true,
    sections: 5,
  },
];
