import type { StockSpec, StockStripe } from '../types.ts';

// MTR heavy rail. Dimensions from the builders' specifications (Wikipedia, MTR); colors estimated from photos.
// Every MTR heavy rail line runs under overhead wires, so all trains carry pantographs.
const STEEL = '#C3C7CB';
const ROOF = '#6E7176';
const GLASS = '#1B2026';
const MASK = '#1C1E22';
const MTR_RED = '#D2202F';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

/** Tung Chung line (A-Trains, and the K-Trains wrapped to match): metallic gray over beige, red line under the windows. */
const tclLivery = {
  body: '#8F969D',
  roof: '#7D8186',
  front: '#8F969D',
  doorColor: '#8F969D',
  windowColor: GLASS,
  skirt: '#C9BFA6',
  stripes: [band('#D8CFB9', 0, 0.43), band('#C8323C', 0.43, 0.46)],
  frontStripes: [band('#1D1F23', 0.45, 0.9), band(MTR_RED, 0.3, 0.37)],
  pantograph: true,
};

/** "Railway Vision" livery of MTR trains delivered since 2016: stainless sides, dark window band, red line along the roof. */
const newMtr = {
  finish: 'stainless' as const,
  body: '#BDC1C5',
  roof: '#8A8E93',
  front: '#2A2D32',
  doorColor: '#BDC1C5',
  windowColor: GLASS,
  skirt: '#4C5056',
  stripes: [band('#2C2F34', 0.5, 0.84), band(MTR_RED, 0.87, 0.93)],
  frontStripes: [band(MTR_RED, 0.26, 0.33)],
  pantograph: true,
};

export const stock: StockSpec[] = [
  {
    id: 'hongkong-m-train',
    name: 'M-Train',
    maker: 'Metro-Cammell / GEC Alsthom',
    introduced: 1979,
    blurb: "Built in Birmingham, England, these trains opened Hong Kong's first metro line in 1979. Q-Trains are now retiring them.",
    length: 22.2,
    width: 3.11,
    height: 3.7,
    doors: 5,
    profile: 'box',
    nose: 'flat',
    finish: 'stainless',
    body: STEEL,
    roof: ROOF,
    front: MASK,
    doorColor: STEEL,
    windowColor: GLASS,
    frontStripes: [band(MTR_RED, 0.4, 0.48)],
    pantograph: true,
  },
  {
    id: 'hongkong-q-train',
    name: 'Q-Train',
    maker: 'CRRC Qingdao Sifang',
    introduced: 2022,
    blurb: '93 were ordered from Qingdao to replace the 1979 M-Trains; the route maps above their doors light up as you ride.',
    length: 22.2,
    width: 3.2,
    height: 3.7,
    doors: 5,
    profile: 'box',
    nose: 'slant',
    ...newMtr,
    body: '#C3C6C9',
    doorColor: '#8E9398',
    front: '#1C1E21',
  },
  {
    id: 'hongkong-c-train',
    name: 'C-Train',
    maker: 'CNR Changchun',
    introduced: 2011,
    blurb: 'Built in Changchun in northeast China, 22 C-Trains arrived in 2011 to add capacity on the crowded Kwun Tong line.',
    length: 22.1,
    width: 3.12,
    height: 3.73,
    doors: 5,
    profile: 'box',
    nose: 'rounded',
    finish: 'stainless',
    body: STEEL,
    roof: ROOF,
    front: MASK,
    doorColor: STEEL,
    windowColor: GLASS,
    stripes: [band(MTR_RED, 0.46, 0.49)],
    frontStripes: [band('#F2F2F2', 0.2, 0.27), band(MTR_RED, 0.27, 0.36)],
    pantograph: true,
  },
  {
    id: 'hongkong-k-train',
    name: 'K-Train',
    maker: 'Hyundai Rotem / Mitsubishi',
    introduced: 2002,
    blurb: 'Korean-built with Mitsubishi electrics, the K-Train started on the Kwun Tong line in 2002 and moved to Tseung Kwan O in 2010.',
    length: 22.4,
    width: 3.12,
    height: 3.7,
    doors: 5,
    profile: 'box',
    nose: 'flat',
    finish: 'stainless',
    body: STEEL,
    roof: ROOF,
    front: MASK,
    doorColor: STEEL,
    windowColor: GLASS,
    frontStripes: [band(MTR_RED, 0.3, 0.37)],
    pantograph: true,
  },
  {
    id: 'hongkong-tcl-a-train',
    name: 'A-Train (Tung Chung line)',
    maker: 'Adtranz / CAF',
    introduced: 1998,
    blurb: 'Built in Spain for the 1998 opening of the railway to the new airport on Chek Lap Kok, an island mostly reclaimed from the sea.',
    length: 23.0,
    width: 3.1,
    height: 3.7,
    doors: 5,
    profile: 'box',
    nose: 'slant',
    finish: 'paint',
    ...tclLivery,
  },
  {
    id: 'hongkong-tcl-k-train',
    name: 'K-Train (Tung Chung line)',
    maker: 'Rotem',
    introduced: 2006,
    blurb: 'Four Korean-built K-Trains joined the Tung Chung line in 2006, wrapped in vinyl to match the Spanish A-Trains around them.',
    length: 22.4,
    width: 3.12,
    height: 3.7,
    doors: 5,
    profile: 'box',
    nose: 'slant',
    finish: 'paint',
    ...tclLivery,
  },
  {
    id: 'hongkong-ael-a-train',
    name: 'A-Train (Airport Express)',
    maker: 'Adtranz / CAF',
    introduced: 1998,
    blurb: 'Hong Kong station to the airport in about 24 minutes, and you can check in your bags in town before you board.',
    length: 23.0,
    width: 3.1,
    height: 3.7,
    doors: 2,
    profile: 'box',
    nose: 'slant',
    // Bright blue over a cream lower body, split by a teal line that sweeps up at the car ends.
    finish: 'paint',
    body: '#2F5DC3',
    roof: '#3A4C78',
    front: '#2F5DC3',
    doorColor: '#2F5DC3',
    windowColor: GLASS,
    skirt: '#D6D2C6',
    stripes: [band('#E5E2D8', 0, 0.4), band('#F4F4F2', 0.4, 0.415), band('#1E9E96', 0.415, 0.45)],
    frontStripes: [band('#1D1F23', 0.45, 0.9), band(MTR_RED, 0.3, 0.37)],
    pantograph: true,
  },
  {
    id: 'hongkong-r-train',
    name: 'R-Train',
    maker: 'Hyundai Rotem',
    introduced: 2021,
    blurb: 'Nine cars long, one of them First Class. These Korean-built trains took the East Rail line across the harbor in 2022.',
    length: 24.3,
    width: 3.22,
    height: 4.18,
    doors: 5,
    profile: 'box',
    nose: 'slant',
    ...newMtr,
    body: '#C8CACC',
    doorColor: '#C8CACC',
    front: '#25282C',
    stripes: [band('#4A4E54', 0.42, 0.86), band(MTR_RED, 0.88, 0.94)],
  },
  {
    id: 'hongkong-sp1900',
    name: 'SP1900 / SP1950',
    maker: 'Kinki Sharyo / Kawasaki (Itochu)',
    introduced: 2001,
    blurb: 'Built in Japan by Kinki Sharyo and Kawasaki, with a gently bullet-shaped nose; it first carried passengers on East Rail in 2001.',
    length: 24.4,
    width: 3.1,
    height: 3.99,
    doors: 5,
    profile: 'rounded',
    nose: 'bullet',
    finish: 'stainless',
    body: '#C4C7CA',
    roof: '#9A9EA3',
    front: '#D3D6D9',
    doorColor: '#C9453D',
    windowColor: GLASS,
    skirt: '#8C9096',
    frontStripes: [band('#1B1D21', 0.5, 0.86)],
    pantograph: true,
  },
  {
    id: 'hongkong-tml-c-train',
    name: 'TML C-Train',
    maker: 'CRRC Changchun',
    introduced: 2017,
    blurb: 'Built in Changchun for the Sha Tin to Central Link. It first ran in 2017 and now covers the whole 56 km Tuen Ma line.',
    length: 24.4,
    width: 3.1,
    height: 3.99,
    doors: 5,
    profile: 'box',
    nose: 'rounded',
    ...newMtr,
    body: '#C9CBCC',
    doorColor: '#C9CBCC',
    stripes: [band('#3F444A', 0.42, 0.87), band(MTR_RED, 0.88, 0.94)],
  },
  {
    id: 'hongkong-s-train',
    name: 'S-Train',
    maker: 'CNR Changchun',
    introduced: 2016,
    blurb: 'Driverless three-car trains that tunnel under the hills from Admiralty and cross the water to Ap Lei Chau, since 2016.',
    length: 22.1,
    width: 3.12,
    height: 3.73,
    doors: 5,
    profile: 'box',
    nose: 'rounded',
    ...newMtr,
    stripes: [band('#24272C', 0.42, 0.87), band(MTR_RED, 0.88, 0.94)],
    frontStripes: [band(MTR_RED, 0.28, 0.34)],
  },
  {
    id: 'hongkong-drl',
    name: 'Disneyland Resort Line train',
    maker: 'Metro-Cammell, rebuilt by United Goninan',
    introduced: 2005,
    blurb: 'Rebuilt M-Trains with Mickey-shaped windows and handholds and bronze Disney figures inside, running driverless since 2005.',
    length: 22.2,
    width: 3.11,
    height: 3.7,
    doors: 3,
    profile: 'rounded',
    nose: 'rounded',
    finish: 'paint',
    // White cars under a royal blue roof. The Mickey-head windows are dark glass ringed in red: the red goes on
    // the window band, which is as close as the model gets without a Mickey window pattern.
    body: '#F2F1EC',
    roof: '#2D3A8C',
    front: '#2D3A8C',
    doorColor: '#F2F1EC',
    windowColor: '#2A2C30',
    skirt: '#2D3A8C',
    stripes: [band('#C8283A', 0.5, 0.53), band('#2D3A8C', 0.9, 1)],
    frontStripes: [band('#D22F3A', 0.26, 0.32), band('#F2C12E', 0.32, 0.36)],
    pantograph: true,
  },
];
