import type { StockSpec } from '../types.ts';

// TfL corporate and mode colors (TfL Colour Standard, issue 11).
const WHITE = '#F2F2F0';
const RED = '#DC241F';
const BLUE = '#0019A8';
const ROOF = '#8E9296';
const BLACK = '#1B1B1B';
const OVERGROUND_ORANGE = '#FA7B05';
const DLR_RED = '#D2232A';
const TURQUOISE = '#00AFAD';
const TRAM_GREEN = '#5FB526';
/** Deep blue-purple lower bodyside of the Class 345. */
const ELIZABETH_INDIGO = '#2E2A6B';
const DLR_BLUE = '#1C3F94';
const DLR_DOOR = '#B4B8BC';

type Livery = Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'skirt' | 'stripes' | 'frontStripes' | 'pantograph'>;

/** Underground corporate livery: white body, red doors and cab, blue skirt. */
const tubeLivery: Livery = {
  body: WHITE,
  finish: 'paint',
  roof: ROOF,
  front: RED,
  doorColor: RED,
  skirt: BLUE,
  pantograph: false,
};

/** London Overground: white body, black window band, orange doors and cab, blue skirt. */
const overgroundLivery: Omit<Livery, 'pantograph'> = {
  body: WHITE,
  finish: 'paint',
  roof: ROOF,
  front: OVERGROUND_ORANGE,
  doorColor: OVERGROUND_ORANGE,
  skirt: BLUE,
  stripes: [{ color: BLACK, from: 0.5, to: 0.8 }],
  frontStripes: [{ color: BLUE, from: 0, to: 0.22 }],
};

/** The Class 378s kept their yellow cab fronts when the rest of the livery was refreshed. */
const capitalstarFront: Pick<StockSpec, 'front' | 'stripes'> = {
  front: '#FFD100',
  stripes: [
    { color: OVERGROUND_ORANGE, from: 0.2, to: 0.23 },
    { color: BLACK, from: 0.5, to: 0.8 },
  ],
};

/** London Trams: silver-white sides with a lime green roof and nose, black window band, blue skirt. */
const tramLivery: Omit<Livery, 'pantograph'> = {
  body: '#E4E6E6',
  finish: 'paint',
  roof: TRAM_GREEN,
  front: TRAM_GREEN,
  doorColor: '#3C4043',
  skirt: BLUE,
  stripes: [
    { color: BLUE, from: 0, to: 0.2 },
    { color: TRAM_GREEN, from: 0.2, to: 0.24 },
    { color: BLACK, from: 0.42, to: 0.86 },
    { color: TRAM_GREEN, from: 0.9, to: 1 },
  ],
};

export const stock: StockSpec[] = [
  {
    id: 'london-1972',
    name: '1972 Stock',
    maker: 'Metro-Cammell',
    introduced: 1972,
    blurb: 'The oldest trains in regular passenger service in the UK: built 1972-74 and still running the Bakerloo line.',
    length: 16.0,
    width: 2.64,
    height: 2.88,
    doors: 4,
    profile: 'tube',
    nose: 'flat',
    ...tubeLivery,
  },
  {
    id: 'london-1973',
    name: '1973 Stock',
    maker: 'Metro-Cammell',
    introduced: 1975,
    blurb: 'Built with extra-long cars and roomy doorway areas so Heathrow travelers have space for their suitcases.',
    length: 17.6,
    width: 2.63,
    height: 2.88,
    doors: 4,
    profile: 'tube',
    nose: 'flat',
    ...tubeLivery,
  },
  {
    id: 'london-1992',
    name: '1992 Stock',
    maker: 'BREL / ABB',
    introduced: 1993,
    blurb: 'Also runs "The Drain", the Waterloo & City shuttle, whose trains have to be lifted out by crane for overhauls.',
    length: 16.2,
    width: 2.62,
    height: 2.87,
    doors: 4,
    profile: 'tube',
    nose: 'rounded',
    ...tubeLivery,
  },
  {
    id: 'london-1995',
    name: '1995 Stock',
    maker: 'GEC Alsthom',
    introduced: 1998,
    blurb: 'Its tunnel from East Finchley to Morden via Bank runs 27.8 km, the longest on the Underground.',
    length: 17.8,
    width: 2.63,
    height: 2.88,
    doors: 4,
    profile: 'tube',
    nose: 'rounded',
    ...tubeLivery,
  },
  {
    id: 'london-1996',
    name: '1996 Stock',
    maker: 'GEC Alsthom',
    introduced: 1997,
    blurb: 'Serves the Jubilee Line Extension, whose stations were the first on the Tube built with platform-edge doors.',
    length: 17.8,
    width: 2.63,
    height: 2.88,
    doors: 4,
    profile: 'tube',
    nose: 'rounded',
    ...tubeLivery,
  },
  {
    id: 'london-2009',
    name: '2009 Stock',
    maker: 'Bombardier',
    introduced: 2009,
    blurb: 'At peak the Victoria line runs 36 of these trains an hour: one every 100 seconds.',
    length: 16.4,
    width: 2.62,
    height: 2.88,
    doors: 4,
    profile: 'tube',
    nose: 'slant',
    ...tubeLivery,
  },
  {
    id: 'london-s7',
    name: 'S7 Stock',
    maker: 'Bombardier',
    introduced: 2012,
    blurb: 'The first air-conditioned Tube trains, and walk-through: you can see from one end of the train to the other.',
    length: 16.0,
    width: 2.82,
    height: 3.68,
    doors: 3,
    profile: 'box',
    nose: 'slant',
    ...tubeLivery,
  },
  {
    id: 'london-s8',
    name: 'S8 Stock',
    maker: 'Bombardier',
    introduced: 2010,
    blurb: "The Met's longer S8 adds forward-facing seat bays for the long run out to Amersham and Chesham.",
    length: 15.9,
    width: 2.82,
    height: 3.68,
    doors: 3,
    profile: 'box',
    nose: 'slant',
    ...tubeLivery,
  },
  {
    id: 'london-345',
    name: 'Class 345 Aventra',
    maker: 'Bombardier / Alstom',
    introduced: 2017,
    blurb: 'At 205 m, each nine-car Elizabeth line train is about as long as two football fields end to end.',
    length: 22.7,
    width: 2.77,
    height: 3.76,
    doors: 3,
    profile: 'box',
    nose: 'slant',
    body: WHITE,
    finish: 'paint',
    roof: '#D9DADC',
    front: WHITE,
    doorColor: '#E6E6E8',
    skirt: ELIZABETH_INDIGO,
    stripes: [
      { color: ELIZABETH_INDIGO, from: 0, to: 0.36 },
      { color: BLACK, from: 0.5, to: 0.82 },
    ],
    frontStripes: [{ color: ELIZABETH_INDIGO, from: 0, to: 0.3 }],
    pantograph: true,
  },
  {
    id: 'london-378-1',
    name: 'Class 378/1 Capitalstar',
    maker: 'Bombardier',
    introduced: 2009,
    blurb: "Tube-style side seats and a cab-end escape stair, handy in Brunel's 1843 Thames Tunnel on the Windrush line.",
    length: 19.8,
    width: 2.8,
    height: 3.77,
    doors: 2,
    profile: 'box',
    nose: 'slant',
    ...overgroundLivery,
    ...capitalstarFront,
    pantograph: false,
  },
  {
    id: 'london-378-2',
    name: 'Class 378/2 Capitalstar',
    maker: 'Bombardier',
    introduced: 2009,
    blurb: 'Dual-voltage: it swaps third-rail shoes for its pantograph as the Mildmay line crosses north London.',
    length: 19.8,
    width: 2.8,
    height: 3.77,
    doors: 2,
    profile: 'box',
    nose: 'slant',
    ...overgroundLivery,
    ...capitalstarFront,
    pantograph: true,
  },
  {
    id: 'london-710',
    name: 'Class 710 Aventra',
    maker: 'Bombardier',
    introduced: 2019,
    blurb: "Built in Derby, the Overground's Class 710s first carried passengers in May 2019, between Gospel Oak and Barking.",
    length: 20.7,
    width: 2.77,
    height: 3.76,
    doors: 2,
    profile: 'box',
    nose: 'slant',
    ...overgroundLivery,
    pantograph: true,
  },
  {
    id: 'london-b92',
    name: 'B90/B92 Stock',
    maker: 'BN (Bombardier)',
    introduced: 1993,
    blurb: 'DLR trains drive themselves and have no cab, so anyone can grab the front seat for a view down the line.',
    length: 28.0,
    width: 2.65,
    height: 3.51,
    doors: 4,
    profile: 'rounded',
    nose: 'flat',
    body: DLR_RED,
    finish: 'paint',
    roof: ROOF,
    front: DLR_RED,
    doorColor: DLR_DOOR,
    skirt: DLR_BLUE,
    stripes: [
      { color: DLR_BLUE, from: 0, to: 0.3 },
      { color: TURQUOISE, from: 0.3, to: 0.33 },
    ],
    pantograph: false,
    sections: 2,
  },
  {
    id: 'london-b2k',
    name: 'B2K Stock',
    maker: 'Bombardier',
    introduced: 2002,
    blurb: 'Built to match the B92s, so the two types couple together and run side by side in the same trains.',
    length: 28.0,
    width: 2.65,
    height: 3.51,
    doors: 4,
    profile: 'rounded',
    nose: 'flat',
    body: DLR_RED,
    finish: 'paint',
    roof: ROOF,
    front: DLR_RED,
    doorColor: DLR_DOOR,
    skirt: DLR_BLUE,
    stripes: [
      { color: DLR_BLUE, from: 0, to: 0.3 },
      { color: TURQUOISE, from: 0.3, to: 0.33 },
    ],
    pantograph: false,
    sections: 2,
  },
  {
    id: 'london-b07',
    name: 'B07 Stock',
    maker: 'Bombardier',
    introduced: 2008,
    blurb: 'Arrived as the DLR stretched to three-car trains; spot them by their black ends and window surrounds.',
    length: 28.0,
    width: 2.65,
    height: 3.51,
    doors: 4,
    profile: 'rounded',
    nose: 'rounded',
    body: DLR_RED,
    finish: 'paint',
    roof: ROOF,
    front: BLACK,
    doorColor: DLR_DOOR,
    skirt: DLR_BLUE,
    stripes: [
      { color: DLR_BLUE, from: 0, to: 0.3 },
      { color: TURQUOISE, from: 0.3, to: 0.33 },
      { color: BLACK, from: 0.5, to: 0.82 },
    ],
    pantograph: false,
    sections: 2,
  },
  {
    id: 'london-b23',
    name: 'B23 Stock',
    maker: 'CAF',
    introduced: 2025,
    blurb: 'A walk-through train as long as three old DLR units; the first rejoined passenger service in September 2026.',
    length: 86.7,
    width: 2.65,
    height: 3.5,
    doors: 12,
    profile: 'rounded',
    nose: 'rounded',
    body: '#ECEAE2',
    finish: 'paint',
    roof: '#ECEAE2',
    front: BLACK,
    doorColor: '#ECEAE2',
    skirt: TURQUOISE,
    stripes: [{ color: TURQUOISE, from: 0, to: 0.45 }],
    pantograph: false,
    sections: 5,
  },
  {
    id: 'london-cr4000',
    name: 'Bombardier CR4000',
    maker: 'Bombardier',
    introduced: 2000,
    blurb: "Based on Cologne's K4000 and built in Vienna, these trams opened Croydon Tramlink in 2000.",
    length: 30.1,
    width: 2.65,
    height: 3.67,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    ...tramLivery,
    pantograph: true,
    sections: 2,
  },
  {
    id: 'london-variobahn',
    name: 'Stadler Variobahn',
    maker: 'Stadler',
    introduced: 2012,
    blurb: 'Swiss-built and five sections long, the Variobahns are a little longer than the original CR4000 trams.',
    length: 32.4,
    width: 2.65,
    height: 3.5,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    ...tramLivery,
    frontStripes: [{ color: BLUE, from: 0, to: 0.2 }],
    pantograph: true,
    sections: 5,
  },
];
