import type { StockSpec } from '../types.ts';

// Madrid fleets in service, fall 2026. Metro de Madrid: narrow-profile lines 1–5 and R (2.30 m cars) and
// wide-profile lines 6–12 (2.80 m cars); the driverless Series 10000 (Line 6) and the new Line 1 trains start in 2027.
// Metro Ligero: Alstom Citadis 302. Renfe Cercanías: Civia 465, 446, 450 double-deckers and, since August 2026,
// Stadler's 453. Dimensions from Metro de Madrid's "Parque de Material Móvil" drawings and Renfe/Wikipedia data.

const GLASS = '#1B2027';
const METRO_WHITE = '#F4F5F7';
const METRO_BLUE = '#1F4DB5';
const METRO_NAVY = '#1C3F94';
const METRO_ROOF = '#9A9EA3';
const CER_WHITE = '#F5F5F5';
const CER_RED = '#D52B1E';
const CER_PURPLE = '#8E2A7F';
const CER_ROOF = '#9A9A9A';
const CER_SKIRT = '#3A3A3A';

/** Renfe Cercanías: white body, red cab, paired red-over-purple bodyside stripes and a thin red line up top. */
const cercanias: Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'windowColor' | 'skirt' | 'stripes' | 'pantograph'> = {
  body: CER_WHITE,
  finish: 'paint',
  roof: CER_ROOF,
  front: CER_RED,
  doorColor: '#E6E7E8',
  windowColor: GLASS,
  skirt: CER_SKIRT,
  stripes: [
    { color: CER_PURPLE, from: 0.22, to: 0.26 },
    { color: CER_RED, from: 0.26, to: 0.3 },
    { color: CER_RED, from: 0.9, to: 0.92 },
  ],
  pantograph: true,
};

/** AnsaldoBreda wide-profile trains styled by Pininfarina: blue face and roof, dark window band, pale lower side. */
function ansaldo(id: string, name: string, introduced: number, blurb: string): StockSpec {
  return {
    id,
    name,
    maker: 'AnsaldoBreda',
    introduced,
    blurb,
    length: 18.0,
    width: 2.8,
    height: 3.87,
    doors: 4,
    profile: 'rounded',
    nose: 'rounded',
    body: '#E6E9EC',
    finish: 'paint',
    roof: '#1D4FC2',
    front: '#1D4FC2',
    doorColor: '#D7DBDF',
    windowColor: GLASS,
    stripes: [
      { color: '#2B2F36', from: 0.45, to: 0.85 },
      { color: '#1D4FC2', from: 0.9, to: 1 },
    ],
    pantograph: true,
  };
}

export const stock: StockSpec[] = [
  // ------------------------------------------------------------------------------------ Metro, narrow profile
  {
    id: 'madrid-metro-2000a',
    name: 'Serie 2000-A',
    maker: 'CAF (with MACOSA and Ateinsa)',
    introduced: 1985,
    blurb: 'Line 1 dates from 1919, and its narrow tunnels take cars just 2.3 m wide, like these boxy CAF trains from 1985.',
    length: 14.72,
    width: 2.3,
    height: 3.34,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    body: METRO_WHITE,
    finish: 'paint',
    roof: METRO_ROOF,
    front: METRO_BLUE,
    doorColor: '#E3E6EA',
    windowColor: GLASS,
    stripes: [
      { color: METRO_NAVY, from: 0.06, to: 0.12 },
      { color: METRO_NAVY, from: 0.95, to: 0.97 },
    ],
    pantograph: true,
  },
  {
    id: 'madrid-metro-2000b',
    name: 'Serie 2000-B',
    maker: 'CAF',
    introduced: 1997,
    blurb: 'Its rounded, fully glazed front earned the 2000-B the nickname "burbuja" (bubble). It still carries most of Line 5.',
    length: 14.72,
    width: 2.3,
    height: 3.34,
    doors: 3,
    profile: 'box',
    nose: 'rounded',
    body: METRO_WHITE,
    finish: 'paint',
    roof: METRO_ROOF,
    front: METRO_BLUE,
    doorColor: '#E3E6EA',
    windowColor: GLASS,
    stripes: [
      { color: METRO_NAVY, from: 0.06, to: 0.12 },
      { color: METRO_NAVY, from: 0.95, to: 0.97 },
    ],
    pantograph: true,
  },
  {
    id: 'madrid-metro-3000',
    name: 'Serie 3000',
    maker: 'CAF',
    introduced: 2006,
    blurb: 'You can walk the whole train end to end, which earned these snake-like CAF sets the nickname "boa".',
    length: 15.0,
    width: 2.3,
    height: 3.52,
    doors: 3,
    profile: 'box',
    nose: 'slant',
    body: METRO_WHITE,
    finish: 'paint',
    roof: METRO_ROOF,
    front: '#1A1C20',
    doorColor: '#2A45A0',
    windowColor: GLASS,
    skirt: '#2A45A0',
    stripes: [
      { color: '#2A45A0', from: 0.22, to: 0.235 },
      { color: '#2A45A0', from: 0.255, to: 0.27 },
    ],
    frontStripes: [{ color: '#2A45A0', from: 0, to: 0.22 }],
    pantograph: true,
  },

  // ------------------------------------------------------------------------------------ Metro, wide profile
  {
    id: 'madrid-metro-5000',
    name: 'Serie 5000',
    maker: 'CAF',
    introduced: 1993,
    blurb: 'Built in 1993, the flat-faced 5000s are the oldest wide-profile trains still carrying passengers, all of them on Line 9.',
    length: 18.01,
    width: 2.8,
    height: 3.55,
    doors: 4,
    profile: 'box',
    nose: 'flat',
    body: '#E6E8EA',
    finish: 'paint',
    roof: METRO_ROOF,
    front: METRO_BLUE,
    doorColor: METRO_BLUE,
    windowColor: GLASS,
    skirt: METRO_BLUE,
    pantograph: true,
  },
  {
    id: 'madrid-metro-6000',
    name: 'Serie 6000',
    maker: 'CAF / Alstom',
    introduced: 1998,
    blurb: 'Most 6000s went to Buenos Aires in 2013. The few left shuttle the TFM stretch of Line 9 out to Arganda del Rey.',
    length: 18.1,
    width: 2.77,
    height: 3.88,
    doors: 4,
    profile: 'box',
    nose: 'slant',
    body: METRO_WHITE,
    finish: 'paint',
    roof: METRO_ROOF,
    front: METRO_BLUE,
    doorColor: METRO_BLUE,
    windowColor: GLASS,
    stripes: [
      { color: METRO_BLUE, from: 0.13, to: 0.145 },
      { color: METRO_BLUE, from: 0.165, to: 0.18 },
    ],
    pantograph: true,
  },
  ansaldo('madrid-metro-7000', 'Serie 7000', 2002, 'Styled by Pininfarina, the Italian house behind many Ferraris, and built by AnsaldoBreda for the wide-profile lines.'),
  ansaldo('madrid-metro-9000', 'Serie 9000', 2006, 'The only series to have carried passengers on every wide-profile line, except the TFM stretch of Line 9.'),
  {
    id: 'madrid-metro-8000',
    name: 'Serie 8000',
    maker: 'CAF / Alstom',
    introduced: 2001,
    blurb: "CAF's 8000s run in 3-car sets on MetroSur and MetroNorte, and in 4-car sets on Line 8, the airport line.",
    length: 18.2,
    width: 2.8,
    height: 3.88,
    doors: 4,
    profile: 'box',
    nose: 'slant',
    body: '#F2F3F4',
    finish: 'paint',
    roof: '#8A8F96',
    front: '#1A1A1A',
    doorColor: '#E5E7EA',
    windowColor: GLASS,
    stripes: [{ color: METRO_BLUE, from: 0, to: 0.2 }],
    pantograph: true,
  },
  {
    id: 'madrid-metro-8400',
    name: 'Serie 8000 (8400 subseries)',
    maker: 'CAF / Alstom',
    introduced: 2010,
    blurb: 'Six cars joined by open gangways make each Circular train one long room. Line 6 has run them since December 2010.',
    length: 18.2,
    width: 2.8,
    height: 3.88,
    doors: 4,
    profile: 'box',
    nose: 'slant',
    body: '#F2F3F4',
    finish: 'paint',
    roof: '#8A8F96',
    front: '#1A1A1A',
    doorColor: METRO_BLUE,
    windowColor: GLASS,
    stripes: [
      { color: METRO_BLUE, from: 0, to: 0.2 },
      { color: '#D62D2D', from: 0.94, to: 0.96 },
    ],
    pantograph: true,
  },

  // ------------------------------------------------------------------------------------ Metro Ligero
  {
    id: 'madrid-citadis',
    name: 'Alstom Citadis 302',
    maker: 'Alstom',
    introduced: 2007,
    blurb: "Metro Ligero's trams keep to the right, while Madrid's Metro trains, unusually, keep to the left.",
    length: 32.34,
    width: 2.4,
    height: 3.3,
    doors: 6,
    profile: 'tram',
    nose: 'rounded',
    body: '#3C86D8',
    finish: 'paint',
    roof: '#A0A4A8',
    front: '#E1251B',
    doorColor: '#EEF1F4',
    windowColor: GLASS,
    skirt: '#2A62B0',
    frontStripes: [{ color: '#FFFFFF', from: 0.3, to: 0.35 }],
    pantograph: true,
    sections: 5,
  },

  // ------------------------------------------------------------------------------------ Cercanías
  {
    id: 'madrid-civia',
    name: 'Civia (Serie 465)',
    maker: 'CAF / Siemens / Alstom',
    introduced: 2003,
    blurb: "Spain's first low-floor commuter trains: Civia cars are modular, so a unit can be built from two to five cars.",
    length: 19.6,
    width: 2.94,
    height: 4.265,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    ...cercanias,
  },
  {
    id: 'madrid-446',
    name: 'Serie 446',
    maker: 'CAF / MACOSA / MTM',
    introduced: 1989,
    blurb: 'Commuters nicknamed the 446s "dodotis", after a diaper brand, because none of their cars has a toilet.',
    length: 25.3,
    width: 2.94,
    height: 4.185,
    doors: 3,
    profile: 'box',
    nose: 'flat',
    ...cercanias,
  },
  {
    id: 'madrid-450',
    name: 'Serie 450 (double-deck)',
    maker: 'GEC Alsthom / CAF',
    introduced: 1990,
    blurb: 'A six-car 450 double-decker seats about a thousand people, five abreast on two decks.',
    length: 26.6,
    width: 2.92,
    height: 4.3,
    doors: 2,
    profile: 'bilevel',
    nose: 'slant',
    ...cercanias,
  },
  {
    id: 'madrid-453',
    name: 'Serie 453 (Stadler)',
    maker: 'Stadler (Albuixech, Valencia)',
    introduced: 2026,
    blurb: 'New in August 2026: single-deck motor cars and double-deck trailers, the first of 114 trains built near Valencia.',
    length: 24.4,
    width: 2.97,
    height: 4.3,
    doors: 2,
    profile: 'bilevel',
    nose: 'rounded',
    ...cercanias,
    front: '#E8472B',
    doorColor: CER_RED,
  },
];
