import type { StockSpec, StockStripe } from '../types.ts';

// Mexico City fleets in service, fall 2026. STC Metro: rubber-tired trains on lines 1–9 and B (2.5 m wide cars,
// nine per train, six on lines 4 and 6) and steel-wheeled trains under catenary on lines A and 12. Tren Ligero
// "El Ajolote" (STE), reopened in May 2026 with 17 new CRRC cars. Tren Suburbano (CAF EMUs, 25 kV).
// Dimensions from STC's fleet pages and Wikipedia; the STC orange, with lime green on the steel-wheeled stock,
// from STC's livery drawings and photos.

const ORANGE = '#EE6A1F';
const ORANGE_NEW = '#F2621E';
const LIME = '#A2CB3A';
const WHITE = '#F2F2EF';
const STEEL = '#B8BCC0';
const SKIRT = '#2C2E31';
const ROOF = '#8E9296';
const FACE = '#26282C';
const GLASS = '#1B2027';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

type Livery = Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'windowColor' | 'skirt' | 'stripes' | 'frontStripes'>;

/** The STC orange of 1969: all-orange body, bare stainless doors, dark underframe. */
const classic: Livery = {
  body: ORANGE,
  finish: 'paint',
  roof: ROOF,
  front: ORANGE,
  doorColor: STEEL,
  windowColor: GLASS,
  skirt: SKIRT,
};

/** Orange over lime green: the steel-wheeled scheme, since repainted onto Line A's FM-86s and Line 8's MP-82s. */
const orangeLime: Livery = {
  body: ORANGE,
  finish: 'paint',
  roof: ROOF,
  front: ORANGE,
  doorColor: STEEL,
  windowColor: GLASS,
  skirt: SKIRT,
  stripes: [band(LIME, 0.05, 0.3)],
  frontStripes: [band(LIME, 0.05, 0.3)],
};

// Rubber-tired cars: 2.5 m wide, 3.6 m tall, four double doors a side; nine cars make a 150 m train.
const pneu = { width: 2.5, height: 3.6, doors: 4, pantograph: false };
// Steel-wheeled cars of lines A and 12 are wider and take power from overhead wires.
const ferreo = { width: 2.8, height: 3.6, doors: 4, pantograph: true };

export const stock: StockSpec[] = [
  // ------------------------------------------------------------------------------------ Line 1
  {
    id: 'mexicocity-nm22',
    name: 'NM-22',
    maker: 'CRRC Zhuzhou',
    introduced: 2024,
    blurb: 'Line 1 reopened end to end in November 2025 after three years of rebuilding, run by 29 of these Chinese-built trains.',
    length: 16.7,
    ...pneu,
    profile: 'rounded',
    nose: 'rounded',
    body: ORANGE_NEW,
    finish: 'paint',
    roof: '#9A9EA2',
    front: WHITE,
    doorColor: ORANGE_NEW,
    windowColor: GLASS,
    skirt: SKIRT,
    frontStripes: [band(FACE, 0, 0.3)],
  },
  {
    id: 'mexicocity-nm16',
    name: 'NM-16',
    maker: 'CAF (built in Mexico)',
    introduced: 2019,
    blurb: 'Ten CAF trains that joined Line 1 in 2019: pale silver cars edged in STC orange, whose door chime sounds like Madrid’s.',
    length: 16.7,
    ...pneu,
    profile: 'rounded',
    nose: 'rounded',
    body: '#E4E6E8',
    finish: 'paint',
    roof: '#A7ABAF',
    front: WHITE,
    doorColor: STEEL,
    windowColor: GLASS,
    skirt: ORANGE,
    stripes: [band(ORANGE, 0.1, 0.14), band(ORANGE, 0.93, 1)],
    frontStripes: [band(ORANGE, 0, 0.3), band(ORANGE, 0.9, 1)],
  },

  // ------------------------------------------------------------------------------------ Classic rubber-tired stock
  {
    id: 'mexicocity-nm02',
    name: 'NM-02',
    maker: 'Bombardier / CAF',
    introduced: 2005,
    blurb: "Line 2's NM-02s were the Metro's first walk-through trains: you can stroll all nine cars from one cab to the other.",
    length: 16.8,
    ...pneu,
    profile: 'rounded',
    nose: 'rounded',
    body: ORANGE,
    finish: 'paint',
    roof: ROOF,
    front: '#E9EAEA',
    doorColor: STEEL,
    windowColor: GLASS,
    skirt: SKIRT,
    stripes: [band(WHITE, 0.08, 0.4)],
    frontStripes: [band(FACE, 0.05, 0.14)],
  },
  {
    id: 'mexicocity-mp68',
    name: 'MP-68 (rebuilt R93/R96)',
    maker: 'Alstom (rebuilt by CAF and Bombardier)',
    introduced: 1969,
    blurb: 'An orange MP-68 made the first Metro trip in September 1969. Rebuilt survivors of that French fleet still run Lines 5 and B.',
    length: 16.8,
    ...pneu,
    profile: 'box',
    nose: 'flat',
    ...classic,
    front: FACE,
    frontStripes: [band(ORANGE, 0, 0.32)],
  },
  {
    id: 'mexicocity-nm73',
    name: 'NM-73 (rehabilitated)',
    maker: 'Concarril (with Alstom)',
    introduced: 1975,
    blurb: 'The first Metro cars built in Mexico, at Concarril in Ciudad Sahagún. Lines 4 and 6 run them cut down to six cars.',
    length: 16.8,
    ...pneu,
    profile: 'box',
    nose: 'flat',
    ...classic,
    stripes: [band(WHITE, 0.22, 0.245), band(WHITE, 0.4, 0.42)],
    frontStripes: [band(WHITE, 0.22, 0.245)],
  },
  {
    id: 'mexicocity-nm79',
    name: 'NM-79',
    maker: 'Concarril (with Alstom)',
    introduced: 1981,
    blurb: 'Opened Line 4 in 1981 and Line 7 in 1984. The first Metro trains with roof fans, inside they are cream with lime-green seats.',
    length: 16.8,
    ...pneu,
    profile: 'box',
    nose: 'slant',
    ...classic,
    body: '#E8541E',
    front: '#E8541E',
  },
  {
    id: 'mexicocity-nc82',
    name: 'NC-82',
    maker: 'Bombardier (Canada)',
    introduced: 1987,
    blurb: "Built in Canada as NM-79 look-alikes. A few play a warped door chime, so riders call them 'borrachos': the drunk ones.",
    length: 16.8,
    ...pneu,
    profile: 'box',
    nose: 'slant',
    ...classic,
  },
  {
    id: 'mexicocity-mp82',
    name: 'MP-82',
    maker: 'Alsthom-Atlantique',
    introduced: 1985,
    blurb: "French cousins of Paris's MP 73. Since 1994 they have run only on Line 8, now in the steel-wheeled trains' orange and lime.",
    length: 16.8,
    ...pneu,
    profile: 'box',
    nose: 'slant',
    ...orangeLime,
  },
  {
    id: 'mexicocity-nm83',
    name: 'NM-83',
    maker: 'Concarril',
    introduced: 1984,
    blurb: 'The last Concarril trains fitted with lime-green seats. 55 of them work Lines 3, 6, 7 and 9.',
    length: 16.8,
    ...pneu,
    profile: 'box',
    nose: 'slant',
    ...classic,
  },
  {
    id: 'mexicocity-ne92',
    name: 'NE-92',
    maker: 'CAF (Spain)',
    introduced: 1994,
    blurb: "'NE' is for Neumático Español: the Metro's first Spanish-built trains, all 15 of them on Line 3.",
    length: 16.8,
    ...pneu,
    profile: 'box',
    nose: 'flat',
    ...classic,
    front: '#44474C',
    frontStripes: [band(ORANGE, 0, 0.3)],
  },

  // ------------------------------------------------------------------------------------ Steel-wheeled stock
  {
    id: 'mexicocity-fm86',
    name: 'FM-86',
    maker: 'Concarril',
    introduced: 1991,
    blurb: "The Metro's first steel-wheeled train opened Line A in 1991 under overhead wires. Its six-car sets have grown to nine.",
    length: 16.7,
    ...ferreo,
    profile: 'box',
    nose: 'slant',
    ...orangeLime,
  },
  {
    id: 'mexicocity-fe07',
    name: 'FE-07',
    maker: 'CAF',
    introduced: 2009,
    blurb: 'The first steel-wheeled Metro train with open gangways. Nine of them help the FM-86s along Line A.',
    length: 16.7,
    ...ferreo,
    profile: 'rounded',
    nose: 'rounded',
    ...orangeLime,
    front: ORANGE,
    frontStripes: [band(FACE, 0.3, 0.4), band(LIME, 0.05, 0.3)],
  },
  {
    id: 'mexicocity-fe10',
    name: 'FE-10',
    maker: 'CAF',
    introduced: 2012,
    blurb: "Line 12's seven-car trains draw 1,500 V from overhead wires, unlike the rest of the Metro, which runs on 750 V.",
    length: 20.0,
    ...ferreo,
    profile: 'rounded',
    nose: 'rounded',
    ...orangeLime,
    frontStripes: [band(FACE, 0.3, 0.4), band(LIME, 0.05, 0.3)],
  },

  // ------------------------------------------------------------------------------------ Tren Ligero "El Ajolote"
  {
    id: 'mexicocity-te25',
    name: 'TE-25',
    maker: 'CRRC Zhuzhou',
    introduced: 2026,
    blurb: '17 of these arrived for the World Cup, when the Tren Ligero was renamed El Ajolote after the axolotl of Xochimilco.',
    length: 29.3,
    width: 2.65,
    height: 3.45,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    body: '#ECEAE3',
    finish: 'paint',
    roof: '#C9CACC',
    front: FACE,
    doorColor: STEEL,
    windowColor: GLASS,
    skirt: '#3A3B3E',
    stripes: [band('#2E2F33', 0.9, 0.97)],
    frontStripes: [band(WHITE, 0, 0.25)],
    pantograph: true,
    sections: 2,
  },
  {
    id: 'mexicocity-te23',
    name: 'TE-23',
    maker: 'CRRC Zhuzhou',
    introduced: 2024,
    blurb: 'The first new Tren Ligero cars in a decade: CRRC delivered nine from late 2023, blue with bright flowers around the cab.',
    length: 29.3,
    width: 2.65,
    height: 3.45,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    body: '#1F5CC8',
    finish: 'paint',
    roof: '#C9CACC',
    front: '#1F5CC8',
    doorColor: STEEL,
    windowColor: GLASS,
    skirt: '#17479E',
    frontStripes: [band(FACE, 0.3, 0.55), band('#E8417A', 0.9, 0.97)],
    pantograph: true,
    sections: 2,
  },
  {
    id: 'mexicocity-te95',
    name: 'TE-95',
    maker: 'Bombardier-Concarril / Siemens',
    introduced: 1995,
    blurb: 'Built in Ciudad Sahagún for Guadalajara, which did not need them, so they went to Xochimilco instead.',
    length: 29.0,
    width: 2.65,
    height: 3.45,
    doors: 4,
    profile: 'tram',
    nose: 'flat',
    body: '#1A4FC4',
    finish: 'paint',
    roof: '#C9CACC',
    front: '#1A4FC4',
    doorColor: STEEL,
    windowColor: GLASS,
    skirt: WHITE,
    stripes: [band(WHITE, 0.05, 0.16)],
    frontStripes: [band(WHITE, 0.05, 0.2)],
    pantograph: true,
    sections: 2,
  },

  // ------------------------------------------------------------------------------------ Tren Suburbano
  {
    id: 'mexicocity-suburbano',
    name: 'EMU Cuautitlán-Buenavista',
    maker: 'CAF',
    introduced: 2008,
    blurb: 'Cousins of Renfe’s Series 447 commuter trains in Spain, built by CAF for standard gauge and 25 kV overhead power.',
    length: 25.8,
    width: 2.94,
    height: 4.2,
    doors: 2,
    profile: 'box',
    nose: 'slant',
    body: WHITE,
    finish: 'paint',
    roof: '#B9BCBF',
    front: WHITE,
    doorColor: '#C62A1E',
    windowColor: GLASS,
    skirt: '#3A3A3A',
    stripes: [band('#C62A1E', 0.05, 0.42), band('#1E1E1E', 0.42, 0.45), band('#C62A1E', 0.94, 1)],
    frontStripes: [band('#C62A1E', 0.05, 0.35), band('#1E1E1E', 0.35, 0.38)],
    pantograph: true,
  },
];
