import type { StockSpec } from '../types.ts';

// Montreal rolling stock, fall 2026. Métro: rubber-tired MPM-10 "Azur" nine-car trains (Orange Line and most of the
// Green) and the 1976 MR-73s (the rest of the Green, six-car trains on the Yellow and Blue). REM: driverless Alstom
// Metropolis Saint-Laurent pairs, coupled into four-car trains at peak. exo: diesel push-pull trains, modeled by
// their coaches (Bombardier MultiLevel on most lines, CRRC and Bombardier BiLevel on Saint-Jérôme).

const STM_BLUE = '#1C5DA8';
const MR73_BLUE = '#2F6CB0';
const REM_GREEN = '#84BD00';
const REM_DARK = '#123C2E';
const GLASS = '#1A2128';
const WHITE = '#ECEEEF';

export const stock: StockSpec[] = [
  {
    id: 'montreal-azur',
    name: 'MPM-10 Azur',
    maker: 'Bombardier / Alstom',
    introduced: 2016,
    blurb: 'Named by public vote for the "clear blue" of the métro. Its nine cars are one long open walkway you can stroll from end to end.',
    length: 16.9,
    width: 2.51,
    height: 3.71,
    doors: 3,
    profile: 'rounded',
    nose: 'rounded',
    body: WHITE,
    finish: 'paint',
    roof: '#C5CACE',
    front: '#E6E9EB',
    doorColor: STM_BLUE,
    windowColor: GLASS,
    skirt: '#2A2E33',
    stripes: [
      { color: STM_BLUE, from: 0.06, to: 0.46 },
      { color: '#F4F6F7', from: 0.46, to: 0.5 },
      { color: STM_BLUE, from: 0.9, to: 0.97 },
    ],
    frontStripes: [{ color: STM_BLUE, from: 0.06, to: 0.3 }],
    pantograph: false,
  },
  {
    id: 'montreal-mr73',
    name: 'MR-73',
    maker: 'Bombardier',
    introduced: 1976,
    blurb: 'Built in La Pocatière and still rolling on rubber tires after 50 years. Its three-note chopper start became the sound of the métro.',
    length: 17.0,
    width: 2.5,
    height: 3.6,
    doors: 4,
    profile: 'box',
    nose: 'flat',
    body: MR73_BLUE,
    finish: 'paint',
    roof: '#AEB4B9',
    front: MR73_BLUE,
    doorColor: MR73_BLUE,
    windowColor: GLASS,
    skirt: '#26292D',
    stripes: [{ color: '#F7F8F9', from: 0.3, to: 0.46 }],
    frontStripes: [{ color: '#F2F3F4', from: 0.3, to: 0.42 }],
    pantograph: false,
  },
  {
    id: 'montreal-rem',
    name: 'Alstom Metropolis Saint-Laurent',
    maker: 'Alstom',
    introduced: 2023,
    blurb: 'No driver on board, so anyone can take the front seat. Its headlights echo the cables of the Champlain Bridge it crosses.',
    length: 19.05,
    width: 2.94,
    height: 3.9,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    body: '#F1F2F2',
    finish: 'paint',
    roof: '#C9CDD0',
    front: REM_GREEN,
    doorColor: REM_DARK,
    windowColor: '#16211D',
    skirt: '#2B3230',
    stripes: [
      { color: REM_GREEN, from: 0.05, to: 0.13 },
      { color: REM_DARK, from: 0.42, to: 0.84 },
    ],
    frontStripes: [{ color: '#1B1F1E', from: 0.4, to: 0.86 }],
    endBand: { color: REM_GREEN, width: 1.4 },
    pantograph: true,
  },
  {
    id: 'montreal-exo-multilevel',
    name: 'Bombardier MultiLevel coach',
    maker: 'Bombardier',
    introduced: 2010,
    blurb: 'Built slim enough to squeeze through the century-old Mount Royal Tunnel, which the REM has since taken over.',
    length: 25.9,
    width: 3.05,
    height: 4.72,
    doors: 2,
    profile: 'bilevel',
    nose: 'flat',
    body: '#C3C8CC',
    finish: 'stainless',
    roof: '#959BA0',
    front: '#B8BDC1',
    doorColor: '#B3B8BC',
    windowColor: GLASS,
    skirt: '#34383C',
    stripes: [
      { color: '#233A8F', from: 0.08, to: 0.3 },
      { color: '#F4F5F6', from: 0.3, to: 0.34 },
      { color: '#4F86D0', from: 0.34, to: 0.38 },
    ],
    frontStripes: [{ color: '#233A8F', from: 0.08, to: 0.3 }],
    pantograph: false,
  },
  {
    id: 'montreal-exo-crrc',
    name: 'CRRC bilevel coach',
    maker: 'CRRC Tangshan',
    introduced: 2024,
    blurb: 'The first Chinese-built coaches in Quebec, and the first on the Saint-Jérôme line in exo\'s own light-blue graphics.',
    length: 25.9,
    width: 3.0,
    height: 4.84,
    doors: 2,
    profile: 'bilevel',
    nose: 'flat',
    body: '#B9BEC2',
    finish: 'paint',
    roof: '#8E9499',
    front: '#3A3F44',
    doorColor: '#A9AEB2',
    windowColor: GLASS,
    skirt: '#3B3F43',
    stripes: [
      { color: '#7AAEF0', from: 0.1, to: 0.3 },
      { color: '#A8E3D8', from: 0.3, to: 0.34 },
    ],
    pantograph: false,
  },
];
