import type { StockSpec, StockStripe } from '../types.ts';

// Oslo rolling stock in service, fall 2026. Dimensions are per car (per whole vehicle for trams). The T-bane is
// all Siemens MX3000 since 2010, the trams all CAF SL18 since the last SL79 ran in September 2025. Vy's trains wear
// the dark teal of the 2019 rebrand, except the Class 72s still in NSB's silver. Colors are estimates from photos.

const GLASS = '#1D2327';
const ROOF = '#9DA3A8';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

type Livery = Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'windowColor' | 'skirt' | 'stripes' | 'frontStripes' | 'pantograph'>;

/** Vy, 2019: dark teal with a black window band and face. */
const vy: Livery = {
  body: '#0F6B60',
  finish: 'paint',
  roof: '#8E989A',
  front: '#1B2324',
  doorColor: '#0F6B60',
  windowColor: GLASS,
  skirt: '#2B3334',
  stripes: [band('#18302E', 0.46, 0.86)],
  frontStripes: [band('#0F6B60', 0, 0.3)],
  pantograph: true,
};

export const stock: StockSpec[] = [
  {
    id: 'oslo-mx3000',
    name: 'MX3000',
    maker: 'Siemens',
    introduced: 2006,
    blurb: 'Their brakes feed power back into the third rail, cutting energy use by about 30% against the red trains they replaced.',
    length: 18.1,
    width: 3.16,
    height: 3.7,
    doors: 3,
    profile: 'rounded',
    nose: 'rounded',
    body: '#C7CCD0',
    finish: 'paint',
    roof: ROOF,
    front: '#2A3038',
    doorColor: '#9AA1A7',
    windowColor: GLASS,
    skirt: '#3B4046',
    stripes: [band('#8E959C', 0.42, 0.86)],
    frontStripes: [band('#E8EAEB', 0, 0.3)],
    pantograph: false,
  },
  {
    id: 'oslo-sl18',
    name: 'SL18',
    maker: 'CAF',
    introduced: 2022,
    blurb: 'Oslo’s 87 Urbos trams have cabs at both ends, and at first they announced the stops in Spanish.',
    length: 34.17,
    width: 2.65,
    height: 3.65,
    doors: 1,
    profile: 'tram',
    nose: 'rounded',
    body: '#3B90D0',
    finish: 'paint',
    roof: '#2D6FA6',
    front: '#3B90D0',
    doorColor: '#3B90D0',
    windowColor: GLASS,
    skirt: '#27313A',
    stripes: [band('#2A333C', 0.4, 0.9)],
    frontStripes: [band('#252D35', 0.42, 0.94)],
    pantograph: true,
    sections: 5,
  },
  {
    id: 'oslo-fly71',
    name: 'Class 71',
    maker: 'Adtranz',
    introduced: 1998,
    blurb: 'The airport express, built on the Swedish X2: one unit was once fitted with tilt and sent to try the Bergen Line.',
    length: 20.6,
    width: 3.08,
    height: 3.9,
    doors: 1,
    profile: 'rounded',
    nose: 'bullet',
    body: '#B6BBC0',
    finish: 'paint',
    roof: '#9EA4A9',
    front: '#B6BBC0',
    doorColor: '#C4C8CC',
    windowColor: GLASS,
    skirt: '#7D8388',
    stripes: [band(GLASS, 0.5, 0.8), band('#E8712A', 0.44, 0.47)],
    frontStripes: [band(GLASS, 0.62, 0.86)],
    pantograph: true,
  },
  {
    id: 'oslo-fly78',
    name: 'Class 78 (Oaris)',
    maker: 'CAF',
    introduced: 2021,
    blurb: 'Built for 245 km/h, Flytoget’s CAF trains are held to 210 until the line catches up.',
    length: 26.5,
    width: 2.94,
    height: 3.9,
    doors: 1,
    profile: 'rounded',
    nose: 'bullet',
    body: '#6D7378',
    finish: 'paint',
    roof: '#8C9297',
    front: '#5F656A',
    doorColor: '#6D7378',
    windowColor: GLASS,
    skirt: '#3F4448',
    stripes: [band('#F26B21', 0.36, 0.39), band(GLASS, 0.45, 0.8)],
    frontStripes: [band(GLASS, 0.58, 0.86), band('#F26B21', 0.52, 0.56)],
    pantograph: true,
  },
  {
    id: 'oslo-vy72',
    name: 'Class 72',
    maker: 'AnsaldoBreda',
    introduced: 2002,
    blurb: 'Styled by Pininfarina, they were Norway’s first low-floor trains, and the first painted in green and silver instead of NSB red.',
    length: 21.7,
    width: 3.2,
    height: 4.0,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    body: '#BCC2C6',
    finish: 'paint',
    roof: ROOF,
    front: '#BCC2C6',
    doorColor: '#A7AEB3',
    windowColor: GLASS,
    skirt: '#1C5E6A',
    stripes: [band('#1C5E6A', 0.12, 0.3), band('#C8D23C', 0.3, 0.33)],
    frontStripes: [band('#1C5E6A', 0.12, 0.3), band(GLASS, 0.6, 0.88)],
    pantograph: true,
  },
  {
    id: 'oslo-vy75',
    name: 'Class 75 (FLIRT)',
    maker: 'Stadler',
    introduced: 2012,
    blurb: 'The workhorse of Oslo’s R lines: 83 five-car FLIRTs, the Norwegian cousins of the X74s MTR Express runs in Sweden.',
    length: 21.1,
    width: 3.2,
    height: 4.1,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    ...vy,
  },
  {
    id: 'oslo-vy74',
    name: 'Class 74 (FLIRT)',
    maker: 'Stadler',
    introduced: 2012,
    blurb: 'The InterCity FLIRT: fewer doors and more seats than the 75. The last of Norway’s 150 FLIRTs arrived in 2022.',
    length: 21.2,
    width: 3.2,
    height: 4.1,
    doors: 1,
    profile: 'rounded',
    nose: 'slant',
    ...vy,
  },
];
