import type { StockSpec, StockStripe } from '../types.ts';

// São Paulo fleets in service, fall 2026. Metrô lines 1–3 run broad-gauge (1.6 m), third-rail trains of six 3.1 m
// wide stainless cars: the original Budd-Mafersa and Cobrasma fleets, rebuilt in the 2010s as fleets I–L, next to the
// Alstom and CAF trains of fleets E, G and H. Lines 4, 5 and 6 are standard gauge under catenary. Lines 15 and 17 are
// monorails. CPTM-era lines 7–13 run eight-car EMUs under 3 kV: CPTM red, ViaMobilidade turquoise and TIC Trens orange.
// Dimensions from the Metrô and CPTM fleet pages (pt.wikipedia); colors from photos.

const STEEL = '#C3C8CC';
const METRO_BLUE = '#1B4FA0';
const FACE = '#1E2125';
const GLASS = '#1B2027';
const ROOF = '#9DA2A7';
const SKIRT = '#3A3D41';
const CPTM_RED = '#D9262C';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

type Livery = Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'windowColor' | 'skirt' | 'stripes' | 'frontStripes'>;

/** Metrô's look since 1974: bare stainless steel with Metrô-blue bands. */
const metro = (front: string, frontStripes?: StockStripe[]): Livery => ({
  body: STEEL,
  finish: 'stainless',
  roof: ROOF,
  front,
  doorColor: STEEL,
  windowColor: GLASS,
  skirt: SKIRT,
  stripes: [band(METRO_BLUE, 0.3, 0.34), band(METRO_BLUE, 0.36, 0.38)],
  frontStripes,
});

/** CPTM red, with a black face. */
const cptm: Livery = {
  body: CPTM_RED,
  finish: 'paint',
  roof: '#A9ADB1',
  front: CPTM_RED,
  doorColor: '#C42228',
  windowColor: GLASS,
  skirt: SKIRT,
  stripes: [band('#B71E24', 0, 0.06)],
  frontStripes: [band(FACE, 0.28, 0.62)],
};

// Metrô lines 1–3: 21.75 m cars, 3.1 m wide, four double doors a side, third rail.
const broad = { length: 21.75, width: 3.1, height: 3.62, doors: 4, pantograph: false };
// CPTM-era lines: 21 m cars, 3.05 m wide, four doors a side, 3 kV DC catenary.
const cptmCar = { length: 21.25, width: 3.05, height: 4.0, doors: 4, pantograph: true };

export const stock: StockSpec[] = [
  // ------------------------------------------------------------------------------------ Metrô lines 1–3
  {
    id: 'saopaulo-frota-e',
    name: 'Frota E "Milênio"',
    maker: 'Alstom',
    introduced: 1999,
    blurb: "Riders named them 'Milênio' in a 1999 contest. The 11 Alstom trains are now Line 1's reserve fleet.",
    ...broad,
    height: 3.57,
    profile: 'box',
    nose: 'slant',
    ...metro(METRO_BLUE),
    doorColor: METRO_BLUE,
  },
  {
    id: 'saopaulo-frota-g',
    name: 'Frota G',
    maker: 'Alstom',
    introduced: 2009,
    blurb: "Built at Alstom's Lapa works in São Paulo for Line 2, the 16 G trains now run only on Line 3.",
    ...broad,
    profile: 'box',
    nose: 'rounded',
    ...metro('#E9ECEE', [band('#12A0B8', 0.12, 0.2)]),
    doorColor: METRO_BLUE,
  },
  {
    id: 'saopaulo-frota-h',
    name: 'Frota H',
    maker: 'CAF',
    introduced: 2010,
    blurb: 'CAF opened a factory in Hortolândia to build them: two came from Spain and the other 15 were made in Brazil.',
    ...broad,
    length: 22.1,
    profile: 'box',
    nose: 'slant',
    ...metro('#E9ECEE', [band(METRO_BLUE, 0.12, 0.2)]),
  },
  {
    id: 'saopaulo-frota-i',
    name: 'Frota I',
    maker: 'Budd-Mafersa, rebuilt by Alstom / Siemens',
    introduced: 1974,
    blurb: "Half of Line 1's original 1974 Budd-Mafersa fleet, rebuilt by Alstom and Siemens. They now serve Line 2.",
    ...broad,
    width: 3.18,
    profile: 'box',
    nose: 'slant',
    ...metro('#F0F1F2', [band(METRO_BLUE, 0.1, 0.16)]),
  },
  {
    id: 'saopaulo-frota-j',
    name: 'Frota J',
    maker: 'Budd-Mafersa, rebuilt by Bombardier / Tejofran / Temoinsa',
    introduced: 1974,
    blurb: 'The other half of the 1974 fleet, rebuilt by a Bombardier-led team with an all-new face and air conditioning.',
    ...broad,
    width: 3.18,
    profile: 'box',
    nose: 'slant',
    ...metro(STEEL, [band(METRO_BLUE, 0.2, 0.25), band(METRO_BLUE, 0.27, 0.3)]),
    doorColor: METRO_BLUE,
  },
  {
    id: 'saopaulo-frota-k',
    name: 'Frota K',
    maker: 'Cobrasma, rebuilt by T’Trans / MPE / Temoinsa',
    introduced: 1979,
    blurb: 'Rebuilt Cobrasma trains that never left Line 3 until June 2025, when K11 first carried riders on Line 1.',
    ...broad,
    profile: 'box',
    nose: 'slant',
    ...metro('#EEF0F2', [band(METRO_BLUE, 0.1, 0.22)]),
  },
  {
    id: 'saopaulo-frota-l',
    name: 'Frota L',
    maker: 'Mafersa, rebuilt by Alstom / IESA',
    introduced: 1982,
    blurb: 'Rebuilt Mafersa trains that gained air conditioning yet use less power than before, thanks to new AC motors.',
    ...broad,
    profile: 'box',
    nose: 'slant',
    ...metro('#D9DDE0', [band(METRO_BLUE, 0.2, 0.3)]),
  },

  // ------------------------------------------------------------------------------------ Lines 4, 5, 6
  {
    id: 'saopaulo-rotem-l4',
    name: 'Hyundai Rotem (Line 4)',
    maker: 'Hyundai Rotem',
    introduced: 2010,
    blurb: 'Brazil’s first driverless metro: Line 4-Amarela’s Korean-built trains run with no one in the cab, behind platform doors.',
    length: 21.4,
    width: 2.8,
    height: 3.8,
    doors: 4,
    profile: 'rounded',
    nose: 'rounded',
    body: STEEL,
    finish: 'stainless',
    roof: ROOF,
    front: '#F2C500',
    doorColor: STEEL,
    windowColor: GLASS,
    skirt: SKIRT,
    stripes: [band('#F2C500', 0.3, 0.35)],
    frontStripes: [band(FACE, 0, 0.18)],
    pantograph: true,
  },
  {
    id: 'saopaulo-frota-p',
    name: 'Frota P',
    maker: 'CAF',
    introduced: 2017,
    blurb: "Delivered in 2014, they sat idle until 2017 waiting for Line 5's CBTC signals, the only system they are built to run on.",
    length: 22.1,
    width: 2.8,
    height: 3.78,
    doors: 4,
    profile: 'rounded',
    nose: 'rounded',
    ...metro('#EDEFF1', [band(METRO_BLUE, 0.3, 0.5), band('#0E2F6B', 0.5, 0.56)]),
    pantograph: true,
  },
  {
    id: 'saopaulo-serie-600',
    name: 'Série 600',
    maker: 'Alstom',
    introduced: 2026,
    blurb: 'Line 6 opened in July 2026 with these Alstom trains. Every seat faces sideways to make more room for riders.',
    length: 21.8,
    width: 2.9,
    height: 3.8,
    doors: 4,
    profile: 'rounded',
    nose: 'rounded',
    body: '#CDD1D5',
    finish: 'stainless',
    roof: ROOF,
    front: '#F5A13A',
    doorColor: '#F5A13A',
    windowColor: GLASS,
    skirt: SKIRT,
    stripes: [band('#F5A13A', 0.2, 0.24)],
    frontStripes: [band(FACE, 0, 0.62)],
    pantograph: true,
  },

  // ------------------------------------------------------------------------------------ Monorails
  {
    id: 'saopaulo-frota-m',
    name: 'Frota M (Innovia Monorail 300)',
    maker: 'Bombardier',
    introduced: 2014,
    blurb: 'São Paulo’s first monorail: seven-car Bombardier Innovia 300s glide driverless along Line 15’s concrete beams.',
    length: 12.3,
    width: 3.15,
    height: 4.04,
    doors: 2,
    profile: 'monorail',
    nose: 'rounded',
    body: '#EEF0F2',
    finish: 'paint',
    roof: '#D5D8DB',
    front: '#EEF0F2',
    doorColor: '#EEF0F2',
    windowColor: GLASS,
    skirt: '#7A8087',
    stripes: [band(METRO_BLUE, 0.3, 0.34), band('#3A4048', 0.42, 0.88)],
    frontStripes: [band(METRO_BLUE, 0.3, 0.34)],
    pantograph: false,
  },
  {
    id: 'saopaulo-frota-s',
    name: 'Frota S',
    maker: 'CRRC',
    introduced: 2026,
    blurb: 'China’s CRRC built 19 seven-car monorails to add to Line 15. The last one reached São Paulo in August 2026.',
    length: 12.3,
    width: 3.15,
    height: 4.04,
    doors: 2,
    profile: 'monorail',
    nose: 'rounded',
    body: '#E8EAEC',
    finish: 'paint',
    roof: '#D5D8DB',
    front: '#3A4048',
    doorColor: '#E8EAEC',
    windowColor: GLASS,
    skirt: '#7A8087',
    stripes: [band('#8C959A', 0.3, 0.36), band('#3A4048', 0.42, 0.88)],
    pantograph: false,
  },
  {
    id: 'saopaulo-frota-n',
    name: 'Frota N (BYD SkyRail)',
    maker: 'BYD',
    introduced: 2026,
    blurb: 'Line 17’s monorails come from BYD, the electric-car maker. The line opened to Congonhas airport in March 2026.',
    length: 11.4,
    width: 3.2,
    height: 3.9,
    doors: 2,
    profile: 'monorail',
    nose: 'bullet',
    body: '#F1F2F3',
    finish: 'paint',
    roof: '#D8DADC',
    front: '#F1F2F3',
    doorColor: '#F1F2F3',
    windowColor: GLASS,
    skirt: '#8A9096',
    stripes: [band(METRO_BLUE, 0.36, 0.4), band('#2E3338', 0.46, 0.86)],
    frontStripes: [band(METRO_BLUE, 0.36, 0.4)],
    pantograph: false,
  },

  // ------------------------------------------------------------------------------------ CPTM-era lines 7–13
  {
    id: 'saopaulo-9500',
    name: 'Série 9500',
    maker: 'Hyundai Rotem',
    introduced: 2017,
    blurb: 'Hyundai Rotem delivered them 34 months late. Since 2025 TIC Trens has run them on Line 7, with orange cabs.',
    ...cptmCar,
    profile: 'rounded',
    nose: 'rounded',
    body: STEEL,
    finish: 'stainless',
    roof: ROOF,
    front: '#F07A1A',
    doorColor: '#F07A1A',
    windowColor: GLASS,
    skirt: SKIRT,
    stripes: [band('#D9262C', 0.3, 0.33), band('#1F4DA0', 0.33, 0.36)],
    frontStripes: [band(FACE, 0.3, 0.6)],
  },
  {
    id: 'saopaulo-8900',
    name: 'Série 8900',
    maker: 'Alstom',
    introduced: 2023,
    blurb: 'Alstom built 36 of them for ViaMobilidade, which took over Lines 8 and 9 in 2022, in its turquoise livery.',
    ...cptmCar,
    length: 20.9,
    profile: 'rounded',
    nose: 'rounded',
    body: '#35C3BD',
    finish: 'paint',
    roof: '#B8BEC2',
    front: '#35C3BD',
    doorColor: '#C9CED2',
    windowColor: GLASS,
    skirt: '#4A5055',
    stripes: [band('#C9CED2', 0.45, 0.9)],
    frontStripes: [band('#A7AFB5', 0.62, 0.9), band(FACE, 0.3, 0.62)],
  },
  {
    id: 'saopaulo-7000',
    name: 'Série 7000/7500',
    maker: 'CAF',
    introduced: 2010,
    blurb: 'Built in two batches for Lines 8 and 12. Each train is two four-car units coupled together.',
    ...cptmCar,
    height: 3.93,
    profile: 'rounded',
    nose: 'slant',
    ...cptm,
  },
  {
    id: 'saopaulo-8000',
    name: 'Série 8000',
    maker: 'CAF',
    introduced: 2012,
    blurb: 'Unusually, CPTM rents these 36 trains from CAF rather than owning them. They carry the crowds on Line 11-Coral.',
    ...cptmCar,
    height: 3.93,
    profile: 'rounded',
    nose: 'slant',
    ...cptm,
  },
  {
    id: 'saopaulo-8500',
    name: 'Série 8500',
    maker: 'CAF',
    introduced: 2016,
    blurb: 'They arrived 39 months late, and CPTM fined CAF R$ 8.5 million. They now serve Lines 10, 11 and 12.',
    ...cptmCar,
    profile: 'rounded',
    nose: 'rounded',
    ...cptm,
  },
  {
    id: 'saopaulo-9000',
    name: 'Série 9000',
    maker: 'Alstom',
    introduced: 2014,
    blurb: 'Once the trains of the airport line and its express, these Alstom sets moved to Line 12-Safira.',
    ...cptmCar,
    profile: 'rounded',
    nose: 'rounded',
    ...cptm,
  },
  {
    id: 'saopaulo-2070',
    name: 'Série 2070',
    maker: 'Alstom / Bombardier / CAF',
    introduced: 2008,
    blurb: 'São Paulo’s state audit court ruled their purchase irregular. The six trains still work Line 10-Turquesa.',
    ...cptmCar,
    height: 4.39,
    profile: 'box',
    nose: 'flat',
    ...cptm,
    frontStripes: [band(FACE, 0.45, 0.72)],
  },
  {
    id: 'saopaulo-2500',
    name: 'Série 2500',
    maker: 'CRRC Qingdao Sifang',
    introduced: 2020,
    blurb: 'Eight Chinese-built trains for Line 13-Jade, the rail link to Guarulhos airport, which opened in 2018.',
    ...cptmCar,
    profile: 'rounded',
    nose: 'rounded',
    ...cptm,
    frontStripes: [band(FACE, 0, 0.12), band(FACE, 0.3, 0.62)],
  },
];
