import type { StockSpec } from '../types.ts';

// San Francisco Bay Area fleets in service, fall 2026: BART (Fleet of the Future only; the legacy A/B/C cars
// were retired in 2023–24), eBART DMUs, the Oakland Airport cable liner, Muni's Siemens LRV4s (the Breda LRVs
// left in 2025), the F-line heritage streetcars, the cable cars, and Caltrain's electric and diesel sets.

const GLASS = '#1B232C';
const BART_SILVER = '#C6CBD0';
const BART_WHITE = '#F1F3F4';
const BART_SKY = '#1FA3DC';
const MUNI_RED = '#C8102E';
const CALTRAIN_RED = '#D71F2E';

/** PCC streetcar (1946–48 St. Louis Car Co., single-ended ex-Philadelphia/Newark bodies). */
function pcc(id: string, name: string, introduced: number, blurb: string, livery: Partial<StockSpec>): StockSpec {
  return {
    id,
    name,
    maker: 'St. Louis Car Company',
    introduced,
    blurb,
    length: 14.2,
    width: 2.6,
    height: 3.1,
    doors: 2,
    profile: 'streetcar',
    nose: 'rounded',
    body: '#2F5D3A',
    finish: 'paint',
    roof: '#8E9398',
    front: '#2F5D3A',
    doorColor: '#2F5D3A',
    windowColor: GLASS,
    pantograph: false,
    trolleyPole: true,
    ...livery,
  };
}

export const stock: StockSpec[] = [
  // ---------------------------------------------------------------------------------------------------- BART
  {
    id: 'sf-bart-fotf',
    name: 'Fleet of the Future (D/E cars)',
    maker: 'Bombardier',
    introduced: 2018,
    blurb: 'BART runs on 5 ft 6 in broad gauge, wider than almost any other US railway, so every Fleet of the Future car is custom-built for it.',
    length: 21.3,
    width: 3.2,
    height: 3.85,
    doors: 3,
    profile: 'rounded',
    nose: 'slant',
    body: BART_SILVER,
    finish: 'stainless',
    roof: BART_WHITE,
    front: '#F4F5F3',
    doorColor: BART_SILVER,
    windowColor: GLASS,
    skirt: '#6B737B',
    // The signature full-height blue panel at both ends of every car.
    endBand: { color: '#2A72C8', width: 1.3 },
    pantograph: false,
  },
  {
    id: 'sf-bart-gtw',
    name: 'Stadler GTW 2/6 (eBART)',
    maker: 'Stadler Rail',
    introduced: 2018,
    blurb: 'eBART shuttles to Antioch on standard-gauge track; its Stadler DMUs carry a small power module in the middle of the train.',
    length: 40.9,
    width: 2.95,
    height: 4.0,
    doors: 2,
    profile: 'rounded',
    nose: 'rounded',
    body: BART_WHITE,
    finish: 'paint',
    roof: '#9EA5AC',
    front: BART_WHITE,
    doorColor: '#0068A5',
    windowColor: GLASS,
    skirt: '#0068A5',
    stripes: [{ color: BART_SKY, from: 0.12, to: 0.17 }],
    frontStripes: [{ color: '#0068A5', from: 0, to: 0.14 }],
    pantograph: false,
    sections: 3,
  },
  {
    id: 'sf-bart-cable-liner',
    name: 'Cable Liner (Oakland Airport)',
    maker: 'Doppelmayr Cable Car',
    introduced: 2014,
    blurb: 'The Oakland Airport trains have no motors: a steel cable hauls them 3.2 miles along an elevated guideway.',
    length: 11.5,
    width: 2.8,
    height: 3.4,
    doors: 2,
    profile: 'agt',
    nose: 'rounded',
    body: BART_WHITE,
    finish: 'paint',
    roof: '#D5D9DC',
    front: BART_WHITE,
    doorColor: '#B9C0C6',
    windowColor: GLASS,
    stripes: [{ color: BART_SKY, from: 0.08, to: 0.14 }],
    pantograph: false,
  },

  // ---------------------------------------------------------------------------------------------------- Muni
  {
    id: 'sf-muni-lrv4',
    name: 'LRV4 (Siemens S200 SF)',
    maker: 'Siemens Mobility',
    introduced: 2017,
    blurb: "Built in Sacramento, Muni's LRV4s replaced every Breda car by 2025 and now run the whole Muni Metro.",
    length: 22.86,
    width: 2.65,
    height: 3.3,
    doors: 4,
    profile: 'tram',
    nose: 'slant',
    body: '#D3D7DB',
    finish: 'paint',
    roof: '#E6E8EA',
    front: '#E6E8EA',
    doorColor: '#B8BEC4',
    windowColor: GLASS,
    skirt: '#3B4148',
    stripes: [{ color: MUNI_RED, from: 0.12, to: 0.2 }],
    frontStripes: [{ color: MUNI_RED, from: 0.08, to: 0.3 }],
    pantograph: true,
    sections: 2,
  },
  pcc('sf-muni-pcc-1058', 'PCC 1058 · Chicago', 1948, 'Wears Chicago\'s "Green Hornet" colors: Mercury Green, Croydon Cream and a pinstripe of Swamp Holly Orange.', {
    body: '#2E5E3B',
    front: '#2E5E3B',
    doorColor: '#2E5E3B',
    roof: '#2E5E3B',
    stripes: [
      { color: '#E07A2B', from: 0.44, to: 0.47 },
      { color: '#EFE2BF', from: 0.47, to: 0.9 },
    ],
    frontStripes: [{ color: '#E07A2B', from: 0.44, to: 0.47 }],
  }),
  pcc('sf-muni-pcc-1060', 'PCC 1060 · Philadelphia', 1947, 'A real Philadelphia car in its 1938 silver, cream and blue, nicknamed the "Cream Cheese" car for its packaging look.', {
    body: '#BFC4C8',
    front: '#BFC4C8',
    doorColor: '#BFC4C8',
    roof: '#9FA5AA',
    stripes: [
      { color: '#1F4FA8', from: 0.42, to: 0.46 },
      { color: '#F1E6C8', from: 0.46, to: 0.9 },
      { color: '#1F4FA8', from: 0.9, to: 0.93 },
    ],
    frontStripes: [{ color: '#1F4FA8', from: 0.42, to: 0.46 }],
  }),
  pcc('sf-muni-pcc-1074', 'PCC 1074 · Toronto', 1946, "Painted as one of Toronto's maroon-and-cream \"Red Rockets\", which ran there from 1938 to 1995.", {
    body: '#7E1E24',
    front: '#7E1E24',
    doorColor: '#7E1E24',
    roof: '#7E1E24',
    stripes: [{ color: '#EDE0BE', from: 0.4, to: 0.47 }],
    frontStripes: [{ color: '#EDE0BE', from: 0.4, to: 0.47 }],
  }),
  pcc('sf-muni-pcc-1061', 'PCC 1061 · Pacific Electric', 1948, 'Honors the "Big Red Cars" of Los Angeles in red, orange and silver borrowed from Southern Pacific\'s Daylight trains.', {
    body: '#B3302A',
    front: '#B3302A',
    doorColor: '#B3302A',
    roof: '#B7BCC0',
    stripes: [{ color: '#EE8A2D', from: 0.46, to: 0.88 }],
    frontStripes: [{ color: '#EE8A2D', from: 0.46, to: 0.6 }],
  }),
  pcc('sf-muni-pcc-1052', 'PCC 1052 · Los Angeles Railway', 1948, 'In the two-tone yellow of Los Angeles Railway, the "Yellow Car" line that PCC fans still miss.', {
    body: '#E9B227',
    front: '#E9B227',
    doorColor: '#E9B227',
    roof: '#8E9398',
    stripes: [{ color: '#F6DA72', from: 0.46, to: 0.9 }],
  }),
  {
    id: 'sf-muni-milano',
    name: 'Peter Witt "Milano" tram',
    maker: 'Carminati & Toselli',
    introduced: 1928,
    blurb: "Built in 1928 for Milan, where near-identical Peter Witt trams still run; Muni's wear Milan's 1970s orange.",
    length: 13.3,
    width: 2.35,
    height: 3.3,
    doors: 3,
    profile: 'streetcar',
    nose: 'flat',
    body: '#EB7A1E',
    finish: 'paint',
    roof: '#6E7176',
    front: '#EB7A1E',
    doorColor: '#EB7A1E',
    windowColor: GLASS,
    skirt: '#3A3A3A',
    pantograph: false,
    trolleyPole: true,
  },
  {
    id: 'sf-cable-powell',
    name: 'Powell Street cable car',
    maker: 'Muni Cable Car Shops',
    introduced: 1888,
    blurb: 'Powell cars are single-ended, so at each end of the line the crew spins them around on a turntable by hand.',
    length: 8.4,
    width: 2.4,
    height: 3.1,
    doors: 2,
    profile: 'cablecar',
    nose: 'flat',
    body: '#7A1F2B',
    finish: 'paint',
    roof: '#EDE6D6',
    front: '#7A1F2B',
    doorColor: '#7A1F2B',
    windowColor: '#2A3138',
    stripes: [
      { color: '#8FC6E8', from: 0.36, to: 0.42 },
      { color: '#8FC6E8', from: 0.9, to: 0.96 },
    ],
    pantograph: false,
  },
  {
    id: 'sf-cable-california',
    name: 'California Street cable car',
    maker: 'Muni Cable Car Shops',
    introduced: 1907,
    blurb: 'Longer and double-ended, California cars have open grip sections at both ends and never need a turntable.',
    length: 9.2,
    width: 2.4,
    height: 3.1,
    doors: 2,
    profile: 'cablecar',
    nose: 'flat',
    body: '#7A1F2B',
    finish: 'paint',
    roof: '#EDE6D6',
    front: '#7A1F2B',
    doorColor: '#7A1F2B',
    windowColor: '#2A3138',
    skirt: '#8FC6E8',
    pantograph: false,
  },

  // ---------------------------------------------------------------------------------------------------- Caltrain
  {
    id: 'sf-caltrain-kiss',
    name: 'Stadler KISS EMU',
    maker: 'Stadler (Salt Lake City)',
    introduced: 2024,
    blurb: 'On September 21, 2024 these electric bilevels replaced every Caltrain diesel between San Francisco and San José.',
    length: 26,
    width: 3.05,
    height: 4.6,
    doors: 2,
    profile: 'bilevel',
    nose: 'rounded',
    body: '#E8EAEC',
    finish: 'paint',
    roof: '#A3A9AF',
    front: '#E8EAEC',
    doorColor: '#C9CED3',
    windowColor: GLASS,
    skirt: '#50565C',
    stripes: [{ color: CALTRAIN_RED, from: 0.1, to: 0.17 }],
    frontStripes: [{ color: CALTRAIN_RED, from: 0.1, to: 0.3 }],
    pantograph: true,
  },
  {
    id: 'sf-caltrain-diesel',
    name: 'Bombardier BiLevel (MP36PH-3C diesel)',
    maker: 'Bombardier / MotivePower',
    introduced: 2003,
    blurb: 'The last Caltrain diesels shuttle to Gilroy, because the Union Pacific tracks south of Tamien have no overhead wires.',
    length: 25.9,
    width: 2.95,
    height: 4.8,
    doors: 2,
    profile: 'bilevel',
    nose: 'flat',
    body: '#BEC3C8',
    finish: 'paint',
    roof: '#8D949A',
    front: '#BEC3C8',
    doorColor: '#A9AFB5',
    windowColor: GLASS,
    skirt: '#50565C',
    stripes: [{ color: CALTRAIN_RED, from: 0.12, to: 0.18 }],
    frontStripes: [{ color: CALTRAIN_RED, from: 0.12, to: 0.25 }],
    pantograph: false,
  },
];
