import type { StockSpec, StockStripe } from '../types.ts';

// Stockholm rolling stock in service, fall 2026. Dimensions are per car; the articulated tunnelbana units (C20: three
// bodies, C30: four) and the trams are one 'car' each, split into `sections`. Since March 2026 the red line runs
// only C30s; the C20s work the green and blue lines, where C30s joined them on 31 August 2026. Almost everything
// else wears SL blue. Colors are estimates from photos.

const GLASS = '#1C2329';
const SL_BLUE = '#2F9FE3';
const TRAM_BLUE = '#2E8BD4';
const WHITE = '#EEF0F0';
const STAINLESS = '#BFC4C8';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

type Livery = Pick<StockSpec, 'body' | 'finish' | 'roof' | 'front' | 'doorColor' | 'windowColor' | 'skirt' | 'stripes' | 'frontStripes' | 'pantograph'>;

/** SL trams: all blue, dark window band. */
const tram = (doorColor: string, extra: StockStripe[] = []): Livery => ({
  body: TRAM_BLUE,
  finish: 'paint',
  roof: '#6F8FA8',
  front: TRAM_BLUE,
  doorColor,
  windowColor: GLASS,
  skirt: '#2D5E8C',
  stripes: [band('#223445', 0.42, 0.88), ...extra],
  frontStripes: [band('#1F262D', 0.3, 0.46), band(GLASS, 0.5, 0.92)],
  pantograph: true,
});

export const stock: StockSpec[] = [
  {
    id: 'stockholm-c20',
    name: 'C20',
    maker: 'Adtranz / Bombardier',
    introduced: 1998,
    blurb: 'Every one of the 271 C20s has its own name, suggested by the public. No. 2012 was renamed Estelle when the princess was christened.',
    length: 46.5,
    width: 2.9,
    height: 3.8,
    doors: 2,
    profile: 'box',
    nose: 'flat',
    body: STAINLESS,
    finish: 'stainless',
    roof: '#5E656B',
    front: SL_BLUE,
    doorColor: SL_BLUE,
    windowColor: GLASS,
    skirt: '#8E959B',
    stripes: [band(SL_BLUE, 0.46, 1)],
    frontStripes: [band(STAINLESS, 0, 0.16), band(GLASS, 0.46, 0.9)],
    pantograph: false,
    sections: 3,
  },
  {
    id: 'stockholm-c30',
    name: 'C30',
    maker: 'Bombardier / Alstom',
    introduced: 2020,
    blurb: 'Look closely at the vent grilles under the windows: a few holes are shaped like Pac-Man, hearts and the Three Crowns.',
    length: 70,
    width: 2.92,
    height: 3.8,
    doors: 3,
    profile: 'rounded',
    nose: 'rounded',
    body: WHITE,
    finish: 'paint',
    roof: '#A9AFB4',
    front: '#1D2126',
    doorColor: '#4C8DCB',
    windowColor: GLASS,
    skirt: '#4A5056',
    frontStripes: [band(WHITE, 0, 0.26), band('#E0348F', 0.3, 0.34)],
    pantograph: false,
    sections: 4,
  },
  {
    id: 'stockholm-x60',
    name: 'X60',
    maker: 'Alstom',
    introduced: 2005,
    blurb: 'A 107 m Coradia Nordic with floors level with the platform. Two coupled make a 214 m train for up to 1,750 people.',
    length: 17.8,
    width: 3.26,
    height: 4.28,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    body: '#E4E7E9',
    finish: 'paint',
    roof: '#B3B8BC',
    front: '#E4E7E9',
    doorColor: '#3C8FD6',
    windowColor: GLASS,
    skirt: '#4A5056',
    stripes: [band('#3C8FD6', 0.88, 0.93)],
    frontStripes: [band('#3C8FD6', 0.4, 0.46), band(GLASS, 0.48, 0.92)],
    pantograph: true,
  },
  {
    id: 'stockholm-a32',
    name: 'A32 (Flexity Swift)',
    maker: 'Bombardier',
    introduced: 1999,
    blurb: 'Tvärbanan’s first trams. Six came secondhand from the Dutch RijnGouweLijn; since 2023 all are blue with white doors.',
    length: 29.7,
    width: 2.65,
    height: 3.6,
    doors: 1,
    profile: 'tram',
    nose: 'slant',
    ...tram('#E8ECEE'),
    sections: 3,
  },
  {
    id: 'stockholm-a35',
    name: 'A35 (Urbos AXL)',
    maker: 'CAF',
    introduced: 2013,
    blurb: 'The seat fabric is printed with SL’s rail map as it looked when the trams arrived in the early 2010s.',
    length: 30.8,
    width: 2.65,
    height: 3.6,
    doors: 1,
    profile: 'tram',
    nose: 'rounded',
    ...tram('#E6EBEE', [band('#E8EEF2', 0.3, 0.33), band('#E8EEF2', 0.92, 0.95)]),
    sections: 3,
  },
  {
    id: 'stockholm-a36',
    name: 'A36 (Urbos AXL)',
    maker: 'CAF',
    introduced: 2015,
    blurb: 'A 40 m stretch of the A35 built for Lidingöbanan, which reopened in 2015 rebuilt for 2.65 m wide trams.',
    length: 40,
    width: 2.65,
    height: 3.6,
    doors: 1,
    profile: 'tram',
    nose: 'rounded',
    ...tram('#E6EBEE', [band('#E8EEF2', 0.3, 0.33), band('#E8EEF2', 0.92, 0.95)]),
    sections: 4,
  },
  {
    id: 'stockholm-x10p',
    name: 'X10p',
    maker: 'ABB Railcar / AEG',
    introduced: 1990,
    blurb: 'Roslagsbanan is the last 891 mm narrow-gauge line with regular trains in Sweden; these sets have worked all of it since 1995.',
    length: 19.9,
    width: 2.6,
    height: 3.6,
    doors: 2,
    profile: 'box',
    nose: 'flat',
    body: '#2B57A6',
    finish: 'paint',
    roof: '#8D96A0',
    front: '#2B57A6',
    doorColor: '#E9ECEE',
    windowColor: GLASS,
    skirt: '#26334A',
    stripes: [band('#E7E3D3', 0.3, 0.36)],
    frontStripes: [band('#E7E3D3', 0.3, 0.36), band(GLASS, 0.5, 0.9)],
    pantograph: true,
  },
  {
    id: 'stockholm-x15p',
    name: 'X15p',
    maker: 'Stadler',
    introduced: 2023,
    blurb: 'Swiss-built for Roslagsbanan’s narrow gauge. On a test run one reached 132 km/h, well past the line’s 120 km/h limit.',
    length: 59.7,
    width: 2.75,
    height: 3.9,
    doors: 2,
    profile: 'rounded',
    nose: 'slant',
    body: '#1E9BDF',
    finish: 'paint',
    roof: '#8FA3B2',
    front: '#1E9BDF',
    doorColor: '#EEF1F3',
    windowColor: GLASS,
    skirt: '#1B6FA3',
    stripes: [band('#1E3A52', 0.42, 0.86)],
    frontStripes: [band(GLASS, 0.48, 0.94)],
    pantograph: true,
    sections: 3,
  },
  {
    id: 'stockholm-c10',
    name: 'C10/C11',
    maker: 'ASEA / Hägglunds',
    introduced: 1976,
    blurb: 'Saltsjöbanan’s two-car sets are tunnelbana cars adapted for a railway: middle doors swapped for seats, a skirt to reach the platforms.',
    length: 17.6,
    width: 2.8,
    height: 3.7,
    doors: 2,
    profile: 'box',
    nose: 'flat',
    body: '#2F80C8',
    finish: 'paint',
    roof: '#8C959E',
    front: '#2F80C8',
    doorColor: '#2F80C8',
    windowColor: GLASS,
    skirt: '#2A5E92',
    stripes: [band('#EEF0F0', 0.36, 0.42)],
    frontStripes: [band('#EEF0F0', 0.36, 0.42), band(GLASS, 0.52, 0.88)],
    pantograph: true,
  },
];
