import type { StockSpec, StockStripe } from '../types.ts';

// Sydney Trains, intercity trains, Sydney Metro and light rail. Dimensions from the builders' specifications
// (Wikipedia); colors estimated from photos. Everything runs under 1500 V DC overhead wires (the light rail on 750 V).
const STEEL = '#C5C9CD';
const GLASS = '#1B2026';
const FACE = '#1F2327';
const YELLOW = '#F4B400';
const ORANGE = '#EE6A24';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

/** Sydney's double-deckers: 20 m cars, two wide doors a side at the ends of the lower deck. */
const doubleDeck = {
  length: 20.4,
  width: 3.03,
  height: 4.4,
  doors: 2,
  profile: 'bilevel' as const,
  windowColor: GLASS,
  pantograph: true,
};

export const stock: StockSpec[] = [
  {
    id: 'sydney-waratah-a',
    name: 'Waratah (A set)',
    maker: 'Downer / CRRC Changchun',
    introduced: 2011,
    blurb: "Named after NSW's floral emblem. The car shells were built in Changchun, China, and fitted out at Cardiff near Newcastle.",
    ...doubleDeck,
    nose: 'rounded',
    finish: 'paint',
    body: '#4F5458',
    roof: '#8B9095',
    front: YELLOW,
    doorColor: YELLOW,
    skirt: '#A9AEB2',
    stripes: [band(ORANGE, 0.03, 0.06)],
    frontStripes: [band('#A9AEB2', 0, 0.1), band(FACE, 0.62, 0.9)],
  },
  {
    id: 'sydney-waratah-b',
    name: 'Waratah (B set)',
    maker: 'Downer / CRRC Changchun',
    introduced: 2018,
    blurb: '41 more Waratahs arrived from 2018. Tell them from the A sets by their orange face instead of yellow.',
    ...doubleDeck,
    nose: 'rounded',
    finish: 'paint',
    body: '#55595D',
    roof: '#8B9095',
    front: ORANGE,
    doorColor: YELLOW,
    skirt: '#A9AEB2',
    stripes: [band(ORANGE, 0.03, 0.06)],
    frontStripes: [band('#A9AEB2', 0, 0.1), band(FACE, 0.62, 1)],
  },
  {
    id: 'sydney-tangara',
    name: 'Tangara (T set)',
    maker: 'A Goninan & Co',
    introduced: 1988,
    blurb: "Tangara comes from an Aboriginal word meaning 'to go'. These double-deckers have run on Sydney's suburban lines since 1988.",
    ...doubleDeck,
    nose: 'flat',
    finish: 'stainless',
    body: STEEL,
    roof: '#A7ACB1',
    front: YELLOW,
    doorColor: YELLOW,
    skirt: '#8D9196',
    stripes: [band(YELLOW, 0.1, 0.12)],
    frontStripes: [band('#3A3E42', 0, 0.14), band(FACE, 0.62, 0.9)],
  },
  {
    id: 'sydney-millennium',
    name: 'Millennium (M set)',
    maker: 'EDi Rail',
    introduced: 2002,
    blurb: 'Built by EDi Rail at Cardiff from 2002. These days most of them shuttle on the T6 and T7 lines as four-car sets.',
    ...doubleDeck,
    nose: 'flat',
    finish: 'stainless',
    body: '#A3A7AB',
    roof: '#8E9297',
    front: YELLOW,
    doorColor: '#F29B1D',
    skirt: '#6F7378',
    stripes: [band('#6A6E73', 0.42, 0.9)],
    frontStripes: [band('#B7BBBF', 0, 0.16), band('#3A3F44', 0.3, 0.9)],
  },
  {
    id: 'sydney-oscar',
    name: 'OSCAR (H set)',
    maker: 'UGL Rail',
    introduced: 2006,
    blurb: 'OSCAR stands for Outer Suburban CAR. They were built at Broadmeadow near Newcastle, with toilets aboard for long runs.',
    ...doubleDeck,
    nose: 'rounded',
    finish: 'stainless',
    body: STEEL,
    roof: '#A3A8AD',
    front: '#F07A1E',
    doorColor: '#F07A1E',
    skirt: '#8D9196',
    stripes: [band('#D9A21B', 0.08, 0.1)],
    frontStripes: [band('#2A2D31', 0, 0.12), band(FACE, 0.45, 0.72), band('#262A2E', 0.8, 1)],
  },
  {
    id: 'sydney-mariyung',
    name: 'Mariyung (D set)',
    maker: 'Hyundai Rotem',
    introduced: 2024,
    blurb: 'Mariyung is the Darug word for emu. These intercity trains entered service in December 2024 after a long dispute.',
    ...doubleDeck,
    nose: 'slant',
    finish: 'stainless',
    body: '#C9CDD1',
    roof: '#9EA3A8',
    front: '#3B4046',
    doorColor: ORANGE,
    skirt: '#8D9196',
    stripes: [band('#4A4F55', 0.36, 0.86)],
    frontStripes: [band('#C9CDD1', 0, 0.16), band(ORANGE, 0.22, 0.36)],
  },
  {
    id: 'sydney-metropolis',
    name: 'Metropolis',
    maker: 'Alstom',
    introduced: 2019,
    blurb: "Australia's first driverless metro trains, built by Alstom in Sri City, India. They opened the Metro North West in May 2019.",
    length: 20.25,
    width: 3.035,
    height: 3.7,
    doors: 3,
    profile: 'box',
    nose: 'rounded',
    finish: 'paint',
    body: '#F0F2F3',
    roof: '#C8CCCF',
    front: '#3D444B',
    doorColor: '#F0F2F3',
    windowColor: GLASS,
    skirt: '#9FA4A8',
    stripes: [band('#262B30', 0.44, 0.86), band('#1FB5D3', 0.92, 0.97)],
    frontStripes: [band('#1FB5D3', 0.06, 0.22)],
    pantograph: true,
  },
  {
    id: 'sydney-urbos3',
    name: 'Urbos 3',
    maker: 'CAF',
    introduced: 2014,
    blurb: 'Cracks found in all twelve of these CAF trams halted the Dulwich Hill line in late 2021; borrowed Citadis trams filled in.',
    length: 33,
    width: 2.65,
    height: 3.4,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    finish: 'paint',
    body: '#F3F3F2',
    roof: '#C9CCCE',
    front: '#D7262F',
    doorColor: '#F3F3F2',
    windowColor: GLASS,
    skirt: '#8E1A20',
    stripes: [band('#D7262F', 0, 0.32), band('#D7262F', 0.9, 1)],
    pantograph: true,
    sections: 5,
  },
  {
    id: 'sydney-citadis305',
    name: 'Citadis 305',
    maker: 'Alstom',
    introduced: 2019,
    blurb: "Sydney was the first city to buy Alstom's Citadis X05. They run in coupled pairs 67 m long through George Street.",
    length: 33.5,
    width: 2.65,
    height: 3.4,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    finish: 'paint',
    body: '#ECEDEE',
    roof: '#C6C9CC',
    front: '#1C1D20',
    doorColor: '#2B2E33',
    windowColor: GLASS,
    skirt: '#9E1B20',
    stripes: [band('#D71920', 0, 0.28), band('#2B2E33', 0.36, 0.86), band('#D71920', 0.92, 1)],
    frontStripes: [band('#D71920', 0, 0.24)],
    pantograph: true,
    sections: 5,
  },
  {
    id: 'sydney-urbos100',
    name: 'Urbos 100 (Parramatta)',
    maker: 'CAF',
    introduced: 2024,
    blurb: 'Thirteen seven-module CAF trams opened Parramatta Light Rail in December 2024, running parts of it on batteries alone.',
    length: 45,
    width: 2.65,
    height: 3.4,
    doors: 6,
    profile: 'tram',
    nose: 'rounded',
    finish: 'paint',
    body: '#F3F3F2',
    roof: '#C9CCCE',
    front: '#D7262F',
    doorColor: '#F3F3F2',
    windowColor: GLASS,
    skirt: '#8E1A20',
    stripes: [band('#D7262F', 0, 0.3), band('#D7262F', 0.9, 1)],
    pantograph: true,
    sections: 7,
  },
];
