import type { StockSpec, StockStripe } from '../types.ts';

// Taipei Metro and New Taipei Metro. Dimensions from the builders' specifications (Wikipedia); colors estimated from photos.
// Every metro line runs on a 750 V third rail (Wenhu on guideway power rails), so only the light rail cars carry pantographs.
const STEEL = '#C4C8CC';
const ROOF = '#A4A9AE';
const GLASS = '#1B2026';
const MASK = '#17191C';
const DORTS_BLUE = '#1F5CC0';
const band = (color: StockStripe['color'], from: number, to: number): StockStripe => ({ color, from, to });

/** Unpainted stainless cars with one blue band under the windows, as every high-capacity type wore it until the C381. */
const highCapacity = {
  length: 23.5,
  width: 3.18,
  height: 3.585,
  doors: 4,
  profile: 'box' as const,
  finish: 'stainless' as const,
  body: STEEL,
  roof: ROOF,
  doorColor: STEEL,
  windowColor: GLASS,
  skirt: '#6E7277',
  stripes: [band(DORTS_BLUE, 0.35, 0.42)],
  pantograph: false,
};

export const stock: StockSpec[] = [
  {
    id: 'taipei-c301',
    name: 'C301',
    maker: 'Kawasaki / Union Rail Car',
    introduced: 1997,
    blurb: 'Kawasaki built the shells in Kobe and they were fitted out in Yonkers, New York; these trains opened the Tamsui line in 1997.',
    ...highCapacity,
    nose: 'rounded',
    front: '#B6BBC0',
    frontStripes: [band(MASK, 0.47, 0.92), band(DORTS_BLUE, 0.22, 0.32)],
  },
  {
    id: 'taipei-c321',
    name: 'C321',
    maker: 'Siemens',
    introduced: 1999,
    blurb: "Siemens won this 216-car order in 1993. The flat white fiberglass face sets it apart from the rounded Kawasaki cars.",
    ...highCapacity,
    nose: 'flat',
    front: '#ECECE8',
    frontStripes: [band(MASK, 0.46, 0.96), band(DORTS_BLUE, 0.2, 0.31)],
  },
  {
    id: 'taipei-c341',
    name: 'C341',
    maker: 'Siemens SGP (Vienna)',
    introduced: 2005,
    blurb: 'Only six trains, built in Vienna and bought by the contractor of the Tucheng extension rather than by the city itself.',
    ...highCapacity,
    nose: 'flat',
    front: '#ECECE8',
    frontStripes: [band(MASK, 0.46, 0.96), band(DORTS_BLUE, 0.2, 0.31)],
  },
  {
    id: 'taipei-c371',
    name: 'C371',
    maker: 'Kawasaki / TRSC',
    introduced: 2006,
    blurb: "Taipei's biggest fleet at 321 cars. Much of the second batch was assembled in Taiwan by TRSC from Nippon Sharyo kits.",
    ...highCapacity,
    nose: 'flat',
    front: '#D3D6D9',
    frontStripes: [band(MASK, 0.46, 0.9), band(DORTS_BLUE, 0.22, 0.3)],
  },
  {
    id: 'taipei-c371-xinbeitou',
    name: 'C371 (Xinbeitou set 399)',
    maker: 'Kawasaki',
    introduced: 2009,
    blurb: 'A three-car shuttle painted with hot-spring flowers, running the one stop from Beitou to the Xinbeitou spas since 2009.',
    ...highCapacity,
    nose: 'flat',
    finish: 'paint',
    body: '#4DB3E2',
    front: '#4DB3E2',
    doorColor: '#4DB3E2',
    skirt: '#3A7FA6',
    stripes: [band('#F3C530', 0.82, 0.93), band('#F08A3C', 0.93, 0.98)],
    frontStripes: [band('#F3C530', 0.8, 0.95), band('#2A2D31', 0.52, 0.8)],
  },
  {
    id: 'taipei-c381',
    name: 'C381',
    maker: 'Kawasaki / TRSC',
    introduced: 2012,
    blurb: 'Entered service in October 2012, ahead of the Xinyi and Songshan extensions. Spot it by the double blue stripes.',
    ...highCapacity,
    nose: 'slant',
    front: '#D8DBDE',
    stripes: [band(DORTS_BLUE, 0.33, 0.37), band(DORTS_BLUE, 0.39, 0.43)],
    frontStripes: [band(MASK, 0.47, 0.9), band(DORTS_BLUE, 0.23, 0.28), band(DORTS_BLUE, 0.3, 0.35)],
  },
  {
    id: 'taipei-val256',
    name: 'VAL 256',
    maker: 'Matra / GEC Alsthom',
    introduced: 1996,
    blurb: "Opened Taipei's first metro line in 1996: driverless French VAL cars rolling on rubber tires along an elevated guideway.",
    length: 13.78,
    width: 2.56,
    height: 3.53,
    doors: 2,
    profile: 'agt',
    nose: 'flat',
    finish: 'paint',
    body: '#F1F2F0',
    roof: '#D9DBDD',
    front: '#F1F2F0',
    doorColor: '#F1F2F0',
    windowColor: GLASS,
    skirt: '#2A3F73',
    stripes: [band('#1E4DA6', 0, 0.36)],
    frontStripes: [band('#1E4DA6', 0, 0.32), band(MASK, 0.5, 0.94)],
    pantograph: false,
  },
  {
    id: 'taipei-innovia256',
    name: 'Innovia APM 256',
    maker: 'Bombardier',
    introduced: 2009,
    blurb: "Bombardier's 202 cars came with a moving-block signaling system when the line was extended to Neihu in 2009.",
    length: 13.78,
    width: 2.54,
    height: 3.53,
    doors: 2,
    profile: 'agt',
    nose: 'rounded',
    finish: 'paint',
    body: '#F3F4F2',
    roof: '#DCDEDF',
    front: '#F3F4F2',
    doorColor: '#F3F4F2',
    windowColor: GLASS,
    skirt: '#2A3F73',
    stripes: [band('#1E4FAE', 0, 0.34), band('#45A83A', 0.36, 0.39)],
    frontStripes: [band('#1E4FAE', 0.08, 0.3), band('#45A83A', 0.32, 0.35), band(MASK, 0.5, 0.93)],
    pantograph: false,
  },
  {
    id: 'taipei-c610',
    name: 'Circular line EMU (C610)',
    maker: 'Hitachi Rail Italy / TRSC',
    introduced: 2020,
    blurb: 'Built in Reggio Calabria, Italy. These driverless yellow-nosed trains opened the first section of the Circular line in 2020.',
    length: 17.1,
    width: 2.65,
    height: 3.6,
    doors: 3,
    profile: 'box',
    nose: 'rounded',
    finish: 'paint',
    body: '#F2F2EE',
    roof: '#E4E4E0',
    front: '#F2F2EE',
    doorColor: '#F2F2EE',
    windowColor: GLASS,
    skirt: '#8E9094',
    stripes: [band('#F5BE1B', 0.36, 0.41), band('#1B1C1F', 0.45, 0.87), band('#F5BE1B', 0.91, 0.96)],
    frontStripes: [band('#F5BE1B', 0.4, 0.46), band('#1B1C1F', 0.46, 0.9), band('#F5BE1B', 0.9, 1)],
    pantograph: false,
  },
  {
    id: 'taipei-danhai-lrv',
    name: 'Danhai LRV',
    maker: 'TRSC (design by Voith)',
    introduced: 2018,
    blurb: 'The first light rail cars built in Taiwan. The winning design was repainted sea-blue after its designers visited Tamsui.',
    length: 34.45,
    width: 2.65,
    height: 3.45,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    finish: 'paint',
    // Sea-blue cab modules; the middle modules are white with blue waves along the bottom.
    body: '#F2F8FA',
    roof: '#D4D8DA',
    front: '#58C3E6',
    doorColor: '#F2F8FA',
    windowColor: GLASS,
    skirt: '#3FA9D2',
    stripes: [band('#6CCAEA', 0, 0.3), band('#A8E0F2', 0.3, 0.36), band('#22272C', 0.46, 0.88)],
    frontStripes: [band('#22272C', 0.34, 0.92)],
    pantograph: true,
    sections: 5,
  },
  {
    id: 'taipei-ankeng-lrv',
    name: 'Ankeng LRV',
    maker: 'TRSC',
    introduced: 2023,
    blurb: "Painted 'radiant gold' after a public vote. The line crosses the Xindian River on a cable-stayed bridge with a 130 m tower.",
    length: 34.45,
    width: 2.65,
    height: 3.45,
    doors: 4,
    profile: 'tram',
    nose: 'rounded',
    finish: 'paint',
    body: '#D6C792',
    roof: '#BDB28A',
    front: '#D6C792',
    doorColor: '#CDBE88',
    windowColor: GLASS,
    skirt: '#A89A68',
    stripes: [band('#23272B', 0.46, 0.88)],
    frontStripes: [band('#23272B', 0.3, 0.92)],
    pantograph: true,
    sections: 5,
  },
];
