import { STYLE, type LookConfig } from './look.ts';

// Themes. Every theme draws the same live data and map; a theme is a look (the palette and treatment of
// every material, see look.ts), a sky and light, and at most one gentle post effect. The rules they all follow:
//   1. Trains and lines keep their true colors and stay the clearest things on screen.
//   2. Texture and linework fade to flat fills as you zoom out, so the far view stays calm.
//   3. The style lives in the materials, not in a filter over the finished frame.

export type ThemeId = 'toy' | 'clay' | 'blueprint' | 'subway' | 'neon' | 'pixel' | 'voxel' | 'monet' | 'cubism' | 'noir' | 'circuit' | 'cel';

/** A theme's own sky and light, in place of the real sun (see Atmosphere.style). */
export interface SkyStyle {
  /** Backdrop gradient, top to bottom. */
  top: string;
  bottom: string;
  sun: string;
  sunI: number;
  hemiSky: string;
  hemiGround: string;
  hemiI: number;
  shadows: boolean;
  stars?: boolean;
}

export interface Theme {
  id: ThemeId;
  name: string;
  blurb: string;
  /** Picker thumbnail: a CSS background. */
  swatch: string;
  /** Force the time of day (null = the city's real sky). */
  sky: null | 'day' | 'night';
  /** Replaces the sky gradient and lights (null = the real sky). */
  skyStyle: SkyStyle | null;
  clouds: boolean;
  /** Shadow-edge softness (PCF radius; the default is 3). */
  shadowRadius?: number;
  trees: 'blob' | 'cube';
  /** Pitched roofs on the little houses (default true). */
  roofs?: boolean;
  look: Partial<LookConfig>;
  /** Google Fonts families to load on first use. */
  fonts?: string;
  /** Post-processing: none (draw straight to the screen) or a named effect. */
  post: null | 'neon' | 'pixel' | 'cel';
}

export const THEMES: Theme[] = [
  {
    id: 'toy',
    name: 'Toy',
    blurb: 'Bright little dioramas floating in the clouds',
    swatch: 'linear-gradient(135deg, #7cc3f2 0 40%, #eef0cf 40% 70%, #ff5a5f 70% 80%, #ffd23f 80%)',
    sky: null,
    skyStyle: null,
    clouds: true,
    trees: 'blob',
    look: {},
    post: null,
  },
  {
    id: 'clay',
    name: 'Clay',
    blurb: 'An architect’s white model: only the trains and their lines in color',
    swatch: 'linear-gradient(135deg, #f3f0e9 0 52%, #e8474c 52% 56%, #f3f0e9 56% 70%, #2a7de1 70% 74%, #dcd6ca 74%)',
    sky: 'day',
    skyStyle: { top: '#dcd8cf', bottom: '#f6f4ef', sun: '#fff8ec', sunI: 1.9, hemiSky: '#ffffff', hemiGround: '#dcd6ca', hemiI: 2.15, shadows: true },
    clouds: false,
    trees: 'blob',
    look: {
      style: STYLE.clay,
      land: '#efebe2',
      land2: '#efebe2',
      park: '#e3e5d8',
      green: '#dfe2d3',
      sand: '#f2ede2',
      airport: '#ebe7de',
      runway: '#dbd6cb',
      waterDeep: '#c3cfd5',
      waterShallow: '#d0dade',
      foam: '#eef2f3',
      road: '#f8f6f1',
      motorway: '#fbfaf6',
      rail: '#dcd6ca',
      shore: '#e6ecee',
      detail: 0.08,
      nightK: 0,
      roadGlowK: 0,
      bTint: '#f5f2eb',
      bTintK: 1,
      bRoof: '#fbfaf6',
      bRoofK: 1,
      bWin: 0,
      bLit: 0,
      bLitK: 0,
      bEdge: '#cbc3b4',
      bEdgeK: 0.35,
      bEdgePx: 1,
      suburbWall: '#f2eee6',
      suburbRoof: '#e6e0d4',
      suburbK: 1,
      tree: '#e3e7d6',
      treeK: 1,
      landmark: '#f7f4ee',
      landmarkK: 1,
      slab: '#e4ded1',
      slabK: 1,
      lineDetail: 0.2,
    },
    fonts: 'DM+Sans:wght@400;500;700',
    post: null,
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    blurb: 'Drafted in white ink on engineer’s blue',
    swatch: 'linear-gradient(#ffffff26 1px, transparent 1px) 0 0 / 10px 10px, linear-gradient(90deg, #ffffff26 1px, transparent 1px) 0 0 / 10px 10px, #1f4f8a',
    sky: 'day',
    skyStyle: { top: '#133866', bottom: '#1b4a82', sun: '#ffffff', sunI: 0.9, hemiSky: '#ffffff', hemiGround: '#b4c6de', hemiI: 2.1, shadows: false },
    clouds: false,
    trees: 'blob',
    look: {
      style: STYLE.blueprint,
      land: '#1f4f8a',
      land2: '#1f4f8a',
      park: '#23548f',
      green: '#22538d',
      sand: '#24568f',
      airport: '#21528c',
      runway: '#2b5e97',
      waterDeep: '#17406f',
      waterShallow: '#1a4679',
      foam: '#7fa8d8',
      road: '#33639c',
      motorway: '#3f70a9',
      rail: '#31619a',
      shore: '#9dbfe6',
      detail: 0,
      nightK: 0,
      roadGlowK: 0,
      grid: '#6b97cc',
      gridK: 0.22,
      bTint: '#2a5c97',
      bTintK: 1,
      bRoof: '#2f64a0',
      bRoofK: 1,
      bWin: 0,
      bLit: 0,
      bLitK: 0,
      bEdge: '#e8f1ff',
      bEdgeK: 0.8,
      bEdgePx: 1,
      suburbWall: '#2a5c97',
      suburbRoof: '#2e619c',
      suburbK: 1,
      tree: '#2d629e',
      treeK: 1,
      landmark: '#d6e5fa',
      landmarkK: 1,
      slab: '#173e6c',
      slabK: 1,
      lineWhite: 0.25,
      lineDetail: 0,
    },
    fonts: 'IBM+Plex+Mono:wght@400;500;600;700',
    post: null,
  },
  {
    id: 'subway',
    name: 'NYC Subway',
    blurb: 'Black signs, Helvetica and route bullets, on a diagram-clean map',
    swatch:
      'radial-gradient(circle at 26% 64%, #ee352e 0 15%, transparent 16%), radial-gradient(circle at 50% 64%, #00933c 0 15%, transparent 16%), radial-gradient(circle at 74% 64%, #0039a6 0 15%, transparent 16%), linear-gradient(#000 0 13%, #fff 13% 16%, #000 16%)',
    sky: 'day',
    skyStyle: { top: '#e3e2de', bottom: '#f5f4f0', sun: '#ffffff', sunI: 2.0, hemiSky: '#ffffff', hemiGround: '#c9c6bd', hemiI: 1.8, shadows: true },
    clouds: false,
    trees: 'blob',
    look: {
      style: STYLE.subway,
      land: '#efeeea',
      land2: '#efeeea',
      park: '#c6dcb0',
      green: '#bdd6a7',
      sand: '#ebe5d2',
      airport: '#e6e5e0',
      runway: '#d2d1cc',
      waterDeep: '#8fc0de',
      waterShallow: '#a8d0e6',
      foam: '#dcebf3',
      road: '#ffffff',
      motorway: '#ffffff',
      rail: '#d9d7d0',
      shore: '#ffffff',
      detail: 0.05,
      nightK: 0,
      roadGlowK: 0,
      bTint: '#dcdad4',
      bTintK: 1,
      bRoof: '#e9e7e2',
      bRoofK: 1,
      bWin: 0,
      bLit: 0,
      bLitK: 0,
      bEdge: '#a09d95',
      bEdgeK: 0.3,
      bEdgePx: 1,
      suburbWall: '#e3e1db',
      suburbRoof: '#d5d2cb',
      suburbK: 1,
      tree: '#b5cd9e',
      treeK: 1,
      landmark: '#d9d7d0',
      landmarkK: 0.6,
      slab: '#d9d6cd',
      slabK: 1,
      lineDetail: 0,
      lineCase: '#ffffff',
      lineCaseK: 1,
    },
    fonts: 'Arimo:wght@400;700',
    post: null,
  },
  {
    id: 'neon',
    name: 'Neon',
    blurb: 'A synthwave city that never sleeps',
    swatch: 'linear-gradient(180deg, #12002b 0 55%, #ff2fb3 55% 58%, #12002b 58% 70%, #25e8ff 70% 73%, #12002b 73%)',
    sky: 'night',
    skyStyle: { top: '#05021a', bottom: '#2a0b46', sun: '#9a8cff', sunI: 0.75, hemiSky: '#6252b0', hemiGround: '#0b0719', hemiI: 1.0, shadows: false, stars: true },
    clouds: false,
    trees: 'blob',
    look: {
      style: STYLE.neon,
      land: '#0d0a24',
      land2: '#0d0a24',
      park: '#0b1b26',
      green: '#0a1823',
      sand: '#140f2a',
      airport: '#100c27',
      runway: '#1c1636',
      waterDeep: '#040310',
      waterShallow: '#07061a',
      foam: '#140a30',
      road: '#1f1940',
      motorway: '#2b2152',
      rail: '#1b1635',
      shore: '#140a30',
      detail: 0,
      nightK: 0,
      roadGlow: '#6b45ff',
      roadGlowK: 0.25,
      grid: '#2de2ff',
      gridK: 0.1,
      coastGlow: '#ff2fb3',
      coastGlowK: 0.45,
      bTint: '#17122f',
      bTintK: 1,
      bRoof: '#1d173c',
      bRoofK: 1,
      bWin: 0.1,
      bLit: 0.1,
      bLitCol: '#2de2ff',
      bLitK: 0.6,
      bEdge: '#8a6cff',
      bEdgeK: 0.45,
      bEdgePx: 1,
      suburbWall: '#151032',
      suburbRoof: '#1c1641',
      suburbK: 1,
      tree: '#0d383b',
      treeK: 1,
      landmark: '#2d2458',
      landmarkK: 0.85,
      slab: '#110c29',
      slabK: 1,
      lineWhite: 0.08,
      lineGlow: 1,
      lineDetail: 0,
      trainGlow: 1,
    },
    fonts: 'Orbitron:wght@500;700;900&family=Rajdhani:wght@500;600;700',
    post: 'neon',
  },
  {
    id: 'pixel',
    name: 'Pixel',
    blurb: 'A 90s city-builder: SVGA pixels, grass tiles, asphalt and a black void',
    swatch: 'linear-gradient(#000 0 22%, transparent 22%), conic-gradient(from 45deg, #5f9c3d 0 25%, #58933a 0 50%, #5f9c3d 0 75%, #58933a 0) 0 0 / 10px 10px, #5f9c3d',
    sky: 'day',
    skyStyle: { top: '#000000', bottom: '#0b0f14', sun: '#fff4e0', sunI: 2.5, hemiSky: '#e8eef8', hemiGround: '#5f5848', hemiI: 1.45, shadows: true },
    clouds: false,
    shadowRadius: 0.5,
    trees: 'blob',
    look: {
      style: STYLE.pixel,
      land: '#5f9c3d',
      land2: '#5a9539',
      park: '#44842f',
      green: '#397429',
      sand: '#d6bf78',
      airport: '#7f8a6a',
      runway: '#55575c',
      waterDeep: '#2753b4',
      waterShallow: '#3a73d0',
      foam: '#9fc4ff',
      road: '#5c5d62',
      motorway: '#4d4e54',
      rail: '#7a6a58',
      shore: '#d6bf78',
      detail: 0.2,
      nightK: 0,
      roadGlowK: 0,
      grid: '#4c8631',
      gridK: 0.2,
      bEdge: '#1c1c24',
      bEdgeK: 0.55,
      bEdgePx: 1,
      bSat: 1.15,
      bWin: 0.6,
      tree: '#2f6a24',
      treeK: 0.55,
      slab: '#7a5a3a',
      slabK: 0.6,
      lineDetail: 0,
    },
    fonts: 'Pixelify+Sans:wght@400;600;700&family=Press+Start+2P',
    post: 'pixel',
  },

  {
    id: 'voxel',
    name: 'Voxel',
    blurb: 'The whole city rebuilt in bright blocks',
    swatch: 'conic-gradient(from 45deg, #6fc24a 0 25%, #1f9be4 0 50%, #f2d46a 0 75%, #e0663a 0) 0 0 / 14px 14px',
    sky: 'day',
    skyStyle: { top: '#3fa9ff', bottom: '#c4ecff', sun: '#fff3d6', sunI: 2.7, hemiSky: '#e4f4ff', hemiGround: '#7d9c5a', hemiI: 1.65, shadows: true },
    clouds: true,
    shadowRadius: 1,
    trees: 'cube',
    roofs: false,
    look: {
      style: STYLE.voxel,
      voxel: 8,
      land: '#7cc653',
      land2: '#7cc653',
      park: '#4fb235',
      green: '#3f9f2c',
      sand: '#f4d874',
      airport: '#a9bf8e',
      runway: '#8a8f98',
      waterDeep: '#168de0',
      waterShallow: '#32c4f4',
      foam: '#e8fbff',
      road: '#d2cbbb',
      motorway: '#c2b9a6',
      rail: '#8f8472',
      detail: 0,
      bWin: 0.8,
      bSat: 1.45,
      suburbK: 0,
      tree: '#3fae34',
      treeK: 0.5,
      slab: '#8a5a32',
      slabK: 0.5,
    },
    post: null,
  },

  {
    id: 'monet',
    name: 'Monet',
    blurb: 'An impressionist painting: soft brushwork, lilac shadows, water-lily blues',
    swatch:
      'radial-gradient(ellipse at 30% 35%, #f4c9b8 0 18%, transparent 30%), radial-gradient(ellipse at 70% 70%, #9dc3d6 0 22%, transparent 40%), linear-gradient(135deg, #c9b8e0, #e8dcb4 45%, #9fc584 70%, #6e9cc4)',
    sky: 'day',
    skyStyle: { top: '#b7c9e2', bottom: '#f6dcc6', sun: '#ffe7c4', sunI: 2.0, hemiSky: '#f6eee2', hemiGround: '#c9aa98', hemiI: 1.85, shadows: true },
    clouds: true,
    shadowRadius: 5,
    trees: 'blob',
    look: {
      style: STYLE.monet,
      land: '#e8dcb4',
      land2: '#c3d49a',
      park: '#9fc584',
      green: '#7fb07a',
      sand: '#f1dcb0',
      airport: '#e2dcc0',
      runway: '#c9c3b8',
      waterDeep: '#6a9ac4',
      waterShallow: '#9cc4d8',
      foam: '#dcc2de',
      road: '#f6ecd6',
      motorway: '#f8e4c2',
      rail: '#d6c6b0',
      shore: '#f0e6f2',
      detail: 0.1,
      brushK: 1,
      nightK: 0,
      roadGlowK: 0,
      bTint: '#f2dcc8',
      bTintK: 0.55,
      bRoof: '#d8a898',
      bRoofK: 0.5,
      bWin: 0.25,
      bLit: 0,
      bLitK: 0,
      suburbWall: '#f0dcc6',
      suburbRoof: '#c99a90',
      suburbK: 0.5,
      tree: '#80ae6e',
      treeK: 0.4,
      landmark: '#f0e2cc',
      landmarkK: 0.3,
      slab: '#c9b8a4',
      slabK: 0.8,
      lineWhite: 0.08,
      lineDetail: 0.3,
    },
    fonts: 'Cormorant+Garamond:ital,wght@0,500;0,600;0,700;1,500',
    post: null,
  },
  {
    id: 'cubism',
    name: 'Cubism',
    blurb: 'The city broken into planes, in ochre, olive and slate',
    swatch:
      'conic-gradient(from 20deg at 40% 55%, #cdb07a 0 25%, #4f6f7c 0 40%, #8f9460 0 62%, #b6532f 0 70%, #a99a78 0 88%, #2e241b 0)',
    sky: 'day',
    skyStyle: { top: '#8c7b63', bottom: '#dcc79c', sun: '#fff0d2', sunI: 2.5, hemiSky: '#e6d8b8', hemiGround: '#6b5842', hemiI: 1.25, shadows: true },
    clouds: false,
    shadowRadius: 0.5,
    trees: 'cube',
    look: {
      style: STYLE.cubism,
      land: '#cdb07a',
      land2: '#a99a78',
      park: '#8f9460',
      green: '#737c53',
      sand: '#dcc38e',
      airport: '#bfae88',
      runway: '#8f8574',
      waterDeep: '#4d6d7a',
      waterShallow: '#6f8d94',
      foam: '#b9b6a2',
      road: '#e6d6ae',
      motorway: '#efdcb0',
      rail: '#9a8a70',
      shore: '#e8dcc0',
      detail: 0,
      facetK: 1,
      facetEdge: '#3a2f25',
      nightK: 0,
      roadGlowK: 0,
      bTint: '#b8956a',
      bTintK: 0.75,
      bRoof: '#dcc79c',
      bRoofK: 0.8,
      bWin: 0,
      bLit: 0,
      bLitK: 0,
      bEdge: '#2e241b',
      bEdgeK: 0.7,
      bEdgePx: 1.2,
      suburbWall: '#b99a70',
      suburbRoof: '#8a6a4c',
      suburbK: 0.8,
      tree: '#6f7a4c',
      treeK: 0.8,
      landmark: '#cdb48a',
      landmarkK: 0.6,
      slab: '#7a6650',
      slabK: 1,
      lineDetail: 0,
      lineCase: '#2e241b',
      lineCaseK: 0.8,
    },
    fonts: 'Syne:wght@500;600;700;800',
    post: null,
  },
  {
    id: 'noir',
    name: 'Noir',
    blurb: 'A black-and-white city where only the trains and their lines carry color',
    swatch: 'linear-gradient(115deg, #000 0 38%, #f2f2f2 38% 52%, #000 52% 66%, #e0102a 66% 72%, #000 72%)',
    sky: 'day',
    skyStyle: { top: '#000000', bottom: '#161616', sun: '#ffffff', sunI: 3.1, hemiSky: '#9a9a9a', hemiGround: '#000000', hemiI: 0.55, shadows: true },
    clouds: false,
    shadowRadius: 0.5,
    trees: 'blob',
    look: {
      style: STYLE.noir,
      land: '#1b1b1b',
      land2: '#1b1b1b',
      park: '#2a2a2a',
      green: '#232323',
      sand: '#3a3a3a',
      airport: '#202020',
      runway: '#3c3c3c',
      waterDeep: '#050505',
      waterShallow: '#0b0b0b',
      foam: '#e8e8e8',
      road: '#6a6a6a',
      motorway: '#9a9a9a',
      rail: '#3a3a3a',
      shore: '#f0f0f0',
      detail: 0,
      nightK: 0,
      roadGlowK: 0,
      bTint: '#3c3c3c',
      bTintK: 1,
      bRoof: '#555555',
      bRoofK: 1,
      bWin: 0.5,
      bLit: 0,
      bLitK: 0,
      bEdge: '#d0d0d0',
      bEdgeK: 0.55,
      bEdgePx: 1.2,
      bSat: 0,
      suburbWall: '#444444',
      suburbRoof: '#262626',
      suburbK: 1,
      tree: '#0e0e0e',
      treeK: 1,
      landmark: '#bdbdbd',
      landmarkK: 1,
      slab: '#0a0a0a',
      slabK: 1,
      lineSat: 1,
      lineWhite: 0,
      lineDetail: 0,
      lineCase: '#000000',
      lineCaseK: 0.9,
      trainGlow: 0.35,
    },
    fonts: 'Special+Elite',
    post: null,
  },
  {
    id: 'circuit',
    name: 'Circuit',
    blurb: 'Inside the machine: a black circuit board of cyan traces, where trains are packets of light',
    swatch:
      'linear-gradient(90deg, transparent 0 46%, #19e6ff 46% 54%, transparent 54%), linear-gradient(transparent 0 30%, #19e6ff 30% 36%, transparent 36% 70%, #ffa51f 70% 76%, transparent 76%), #02090c',
    sky: 'night',
    skyStyle: { top: '#000000', bottom: '#021a22', sun: '#7fe8ff', sunI: 0.9, hemiSky: '#2a6a7a', hemiGround: '#000000', hemiI: 0.8, shadows: false, stars: false },
    clouds: false,
    trees: 'cube',
    roofs: false,
    look: {
      style: STYLE.circuit,
      land: '#03100f',
      land2: '#03100f',
      park: '#04161a',
      green: '#041419',
      sand: '#062026',
      airport: '#051417',
      runway: '#0b2a30',
      waterDeep: '#000205',
      waterShallow: '#010609',
      foam: '#021016',
      road: '#0d3a44',
      motorway: '#115260',
      rail: '#0a2a30',
      shore: '#021016',
      detail: 0,
      nightK: 0,
      roadGlow: '#19e6ff',
      roadGlowK: 0.35,
      grid: '#19e6ff',
      gridK: 0.16,
      coastGlow: '#19e6ff',
      coastGlowK: 0.4,
      bTint: '#030c10',
      bTintK: 1,
      bRoof: '#061820',
      bRoofK: 1,
      bWin: 0,
      bLit: 0.12,
      bLitCol: '#ffa51f',
      bLitK: 0.7,
      bEdge: '#19e6ff',
      bEdgeK: 0.85,
      bEdgePx: 1,
      bSat: 1,
      suburbWall: '#04141a',
      suburbRoof: '#062028',
      suburbK: 1,
      tree: '#062a30',
      treeK: 1,
      landmark: '#0c3a44',
      landmarkK: 0.9,
      slab: '#010507',
      slabK: 1,
      lineSat: 1,
      lineWhite: 0.05,
      lineGlow: 0.9,
      lineDetail: 0,
      trainGlow: 0.9,
    },
    fonts: 'Share+Tech+Mono',
    post: 'neon',
  },
  {
    id: 'cel',
    name: 'Cel Shaded',
    blurb: 'A cel-shaded island adventure: lush grass, terracotta roofs, deep blue sea and ink outlines',
    swatch:
      'radial-gradient(ellipse at 50% 120%, #1f63c9 0 34%, transparent 35%), radial-gradient(ellipse at 50% 70%, #f6e6b8 0 30%, transparent 31%), linear-gradient(#4aa3f0 0 38%, #8fd05f 38%)',
    sky: 'day',
    skyStyle: { top: '#3f98ee', bottom: '#c4ebff', sun: '#fff8e6', sunI: 2.9, hemiSky: '#e8f6ff', hemiGround: '#6f8a4a', hemiI: 1.5, shadows: true },
    clouds: true,
    shadowRadius: 0.5,
    trees: 'blob',
    look: {
      style: STYLE.cel,
      land: '#8fcd5e',
      land2: '#86c657',
      park: '#5cb444',
      green: '#3f9a3a',
      sand: '#f6e6b8',
      airport: '#a9cf7c',
      runway: '#8a8578',
      waterDeep: '#1e5fc4',
      waterShallow: '#3ea7e6',
      foam: '#ffffff',
      road: '#ecd7a6',
      motorway: '#f3e2b8',
      rail: '#9a7652',
      shore: '#ffffff',
      detail: 0.4,
      nightK: 0,
      roadGlowK: 0,
      bTint: '#f7ecd4',
      bTintK: 0.55,
      bRoof: '#d4553a',
      bRoofK: 0.4,
      bSat: 1.25,
      bPop: 0.3,
      bWin: 0.55,
      // Building outlines come from the post pass's ink (one line per edge, not a second one in the shader).
      bEdgeK: 0,
      suburbWall: '#f5e9d0',
      suburbRoof: '#c9503a',
      suburbK: 0.55,
      tree: '#3c9b35',
      treeK: 0.6,
      landmark: '#f3e6c8',
      landmarkK: 0.25,
      slab: '#9b6a3e',
      slabK: 0.7,
      lineDetail: 0,
      lineCase: '#2b1d14',
      lineCaseK: 1,
      toon: 1,
    },
    fonts: 'Baloo+2:wght@600;700;800',
    post: 'cel',
  },

];

export const themeById = (id: string | null | undefined) => THEMES.find((t) => t.id === id) ?? THEMES[0];

const KEY = 'tt-theme';

let current: Theme = THEMES[0];
export const activeTheme = () => current;
export function setActiveTheme(t: Theme) {
  current = t;
}
/** `?theme=…` for links, so a shared view opens in the same style (empty for the default). */
export const themeQuery = () => (current.id === 'toy' ? '' : `?theme=${current.id}`);

/** The theme to start with: ?theme= in the URL, else the last one picked on this device. */
export function initialTheme(): Theme {
  const q = new URLSearchParams(location.search).get('theme');
  if (q) return themeById(q);
  try {
    return themeById(localStorage.getItem(KEY));
  } catch {
    return THEMES[0];
  }
}

export function rememberTheme(id: ThemeId) {
  try {
    localStorage.setItem(KEY, id);
  } catch {
    /* private mode: fine */
  }
}

const loaded = new Set<string>();
export function loadFonts(t: Theme) {
  if (!t.fonts || loaded.has(t.fonts)) return;
  loaded.add(t.fonts);
  const l = document.createElement('link');
  l.rel = 'stylesheet';
  l.href = `https://fonts.googleapis.com/css2?family=${t.fonts}&display=swap`;
  document.head.appendChild(l);
}
