// Builds public/data/delhi/transit.json and server/data/delhi/sim.json with the sim kit (docs/KIT_SIM.md).
// Network: OSM route relations (current to the Pink Line ring and the Magenta Line's Majlis Park section, March 2026).
// Trains: DMRC's published average frequencies (delhimetrorail.com/train-frequency, as on 31 Aug 2026) and first/last
// trains from its journey planner. DMRC's static GTFS (otd.delhi.gov.in) dates from Aug 2023 and predates Phase 4, so
// it only informed the run times. Hindi station names are DMRC's own where it lists the station.
// Usage: npx tsx scripts/build-delhi.ts
import { buildSimCity, type DayService, type DayServices, type SimLineConfig } from './lib/osm-network/index.ts';

const mmss = (s: string) => {
  const [m, sec] = s.split(':').map(Number);
  return m + sec / 60;
};

/**
 * DMRC publishes an average peak and off-peak headway per section for weekdays, Saturdays and Sundays ('m:ss').
 * Peaks are 08:00–11:00 and 17:00–20:30; the first hour and late evenings run a little sparser than off-peak.
 */
function dmrc(peak: [string, string, string], off: [string, string, string], first = '06:00', last = '23:00', terminals?: DayService['terminals']): DayServices {
  const day = (p: string, o: string): DayService => {
    const pk = mmss(p), op = mmss(o);
    return {
      first,
      last,
      headways: [[first, op * 1.2], ['07:00', op], ['08:00', pk], ['11:00', op], ['17:00', pk], ['20:30', op], ['22:00', op * 1.3]],
      ...(terminals ? { terminals } : {}),
    };
  };
  return { weekday: day(peak[0], off[0]), saturday: day(peak[1], off[1]), sunday: day(peak[2], off[2]) };
}
/** The same headway all day, every day. */
const flat = (hw: number, first: string, last: string, terminals?: DayService['terminals']): DayServices => ({
  weekday: { first, last, headways: [[first, hw]], ...(terminals ? { terminals } : {}) },
});

const METRO = { vmax: 80, acc: 0.9, dec: 1.0, dwell: 25, dwellInterchange: 45 };

// Official Hindi station names (DMRC, else OSM name:hi), keyed by the OSM English name.
const HINDI: Record<string, string> = {
  "A.I.I.M.S.": "एम्स",
  "Adarsh Nagar": "आदर्श नगर",
  "Akshardham": "अक्षरधाम",
  "Alpha 1": "अल्फ़ा 1",
  "Anand Vihar": "आनंद विहार",
  "Arjan Garh": "अर्जन गढ़",
  "Arthala": "अर्थला",
  "Ashok Park Main": "अशोक पार्क मेन",
  "Ashram": "आश्रम",
  "Azadpur": "आजादपुर",
  "Badarpur": "बदरपुर बॉर्डर",
  "Badhkal Mor": "बड़कल मोड़",
  "Bahadurgarh City": "बहादुरगढ़ सिटी",
  "Barakhambha Road": "बाराखंबा रोड",
  "Bata Chowk": "बाटा चौक",
  "Begumpul": "बेगमपुल",
  "Belvedere Towers": "बेलवेडरे टावर्स",
  "Bhajanpura": "भजनपुरा",
  "Bhalaswa": "भलस्वा",
  "Bhikaji Cama Place": "भीकाजी कामा प्लेस",
  "Botanical Garden": "बोटैनिकल गार्डन",
  "Brigadier Hoshiyar Singh": "ब्रिगेडियर होशियार सिंह",
  "Burari": "बुराड़ी",
  "Central Secretariat": "केंद्रीय सचिवालय",
  "Chandni Chowk": "चांदनी चौक",
  "Chawri Bazaar": "चावड़ी बाज़ार",
  "Chhatarpur": "छतरपुर",
  "Chirag Delhi": "चिराग दिल्ली",
  "Civil Lines": "सिविल लाइंस",
  "Cyber City": "साइबर सिटी",
  "Dabri Mor - Janakpuri South": "डाबरी मोड़- जनकपुरी साउथ",
  "Dashrath Puri": "दशरथपुरी",
  "Deepali Chowk": "दीपाली चौक",
  "Delhi Aerocity": "दिल्ली एयरोसिटी",
  "Delhi Cantt": "दिल्ली कैंट",
  "Delhi Gate": "दिल्ली गेट",
  "Delta 1": "डेल्टा 1",
  "Depot": "डिपो",
  "Dhansa Bus Stand": "ढांसा बस स्टैंड",
  "Dhaula Kuan": "धौला कुआँ",
  "Dilli Haat - INA": "दिल्ली हाट- आईएनए",
  "Dilshad Garden": "दिलशाद गार्डन",
  "DLF Phase 1": "डीएलएफ़ फ़ेज़ 1",
  "DLF Phase 2": "डीएलएफ़ फ़ेज़ 2",
  "Duhai": "दुहाई",
  "Duhai Depot": "दुहाई डिपो",
  "Durgabai Deshmukh South Campus": "दुर्गाबाई देशमुख साउथ कैंपस",
  "Dwarka - Kakrola": "द्वारका",
  "Dwarka Mor": "द्वारका मोड़",
  "Dwarka Sector 10": "द्वारका सेक्टर - 10",
  "Dwarka Sector 11": "द्वारका सेक्टर - 11",
  "Dwarka Sector 12": "द्वारका सेक्टर - 12",
  "Dwarka Sector 13": "द्वारका सेक्टर - 13",
  "Dwarka Sector 14": "द्वारका सेक्टर - 14",
  "Dwarka Sector 21": "द्वारका सेक्टर - 21",
  "Dwarka Sector 8": "द्वारका सेक्टर - 8",
  "Dwarka Sector 9": "द्वारका सेक्टर - 9",
  "East Azad Nagar": "पूर्वी आजाद नगर",
  "East Vinod Nagar - Mayur Vihar - II": "पूर्वी विनोद नगर-मयूर विहार-II",
  "Escorts Mujesar": "एस्कॉर्ट्स मुजेसर",
  "ESI - Basaidarapur": "ईएसआई-बसैदरापुर",
  "Ghaziabad": "गाज़ियाबाद",
  "Ghevra": "घेवरा",
  "Ghitorni": "घिटोरनी",
  "GNIDA Office": "जीएनआईडीए ऑफ़िस",
  "Gokulpuri": "गोकुलपुरी",
  "Govind Puri": "गोविंद पुरी",
  "Greater Kailash": "ग्रेटर कैलाश",
  "Green Park": "ग्रीन पार्क",
  "GTB Nagar": "गुरु तेग बहादुर नगर",
  "Guldhar": "गुलधर",
  "Guru Dronacharya": "गुरु द्रोणाचार्य",
  "Haiderpur Badli Mor": "हैदरपुर बादली मोर",
  "Haiderpur Village": "हैदरपुर गांव",
  "Harkesh Nagar Okhla": "हरकेश नगर ओखला",
  "Hauz Khas": "हौज़ खास",
  "Hindon River": "हिंडन रिवर",
  "IFFCO Chowk": "इफको चौक",
  "IGI Airport": "आईजीआई एयरपोर्ट",
  "IIT Delhi": "आईआईटी दिल्ली",
  "Inderlok": "इन्द्रलोक",
  "Indraprastha": "इंद्रप्रस्थ",
  "IP Extension": "आईपी एक्सटेंशन",
  "ITO": "आईटीओ",
  "Jaffrabad": "जाफ़राबाद",
  "Jagatpur - Wazirabad": "जगतपुर - वज़ीराबाद",
  "Jahangirpuri": "जहांगीरपुरी",
  "Jama Masjid": "जामा मस्जिद",
  "Jamia Millia Islamia": "जामिया मिलिया इस्लामिया",
  "Janakpuri East": "जनकपुरी ईस्ट",
  "Janakpuri West": "जनकपुरी पश्चिम",
  "Jangpura": "जंगपुरा",
  "Janpath": "जनपथ",
  "Jasola Apollo": "जसोला अपोलो",
  "Jasola Vihar Shaheen Bagh": "जसोला विहार शाहीन बाग",
  "Jawaharlal Nehru Stadium": "जवाहरलाल नेहरू स्टेडियम",
  "Jhandewalan": "झंडेवालान",
  "Jharoda Majra": "झारोदा माजरा",
  "Jhilmil": "झिलमिल",
  "Johri Enclave": "जौहरी एन्क्लेव",
  "Jor Bagh": "जोर बाग़",
  "Kailash Colony": "कैलाश कॉलोनी",
  "Kalindi Kunj": "कालिंदी कुंज",
  "Kalkaji Mandir": "कालकाजी मंदिर",
  "Kanhaiya Nagar": "कन्हैया नगर",
  "Karkarduma": "कड़कड़डूमा",
  "Karkarduma Court": "कड़कड़डूमा कोर्ट",
  "Karol Bagh": "करोल बाग़",
  "Kashmere Gate": "कश्मीरी गेट",
  "Kaushambi": "कौशांबी",
  "Keshav Puram": "केशव पुरम",
  "Khajuri Khas": "खजूरी खास",
  "Khan Market": "खान मार्केट",
  "Kirti Nagar": "कीर्ति नगर",
  "Knowledge Park II": "नॉलेज पार्क II",
  "Kohat Enclave": "कोहाट एन्क्लेव",
  "Krishna Nagar": "कृष्णा नगर",
  "Krishna Park Extension": "कृष्णा पार्क एक्सटेंशन",
  "Lajpat Nagar": "लाजपत नगर",
  "Lal Quila": "लाल किला",
  "Laxmi Nagar": "लक्ष्मी नगर",
  "Lok Kalyan Marg": "लोक कल्याण मार्ग",
  "M G Road": "एम.जी. रोड",
  "Madhuban Chowk": "मधुबन चौक",
  "Madipur": "मादीपुर",
  "Majlis Park": "मजलिस पार्क",
  "Malviya Nagar": "मालवीय नगर",
  "Mandawali - West Vinod Nagar": "मंडावली पश्चिम विनोद नगर",
  "Mandi House": "मंडी हाउस",
  "Mansarovar Park": "मानसरोवर पार्क",
  "Maujpur-Babarpur": "मौजपुर-बाबरपुर",
  "Mayapuri": "मायापुरी",
  "Mayur Vihar - I": "मयूर विहार-1",
  "Mayur Vihar Extension": "मयूर विहार एक्सटेंशन",
  "Meerut South": "मेरठ साउथ",
  "Mewala Maharajpur": "मेवाला महाराजपुर",
  "Millennium City Centre Gurugram": "मिलेनियम सिटी सेंटर गुरुग्राम",
  "Model Town": "मॉडल टाउन",
  "Modinagar North": "मोदीनगर नॉर्थ",
  "Modinagar South": "मोदीनगर साउथ",
  "Modipuram": "मोदीपुरम",
  "Mohan Estate": "मोहन एस्टेट",
  "Mohan Nagar": "मोहन नगर",
  "Moolchand": "मूलचंद",
  "Moti Nagar": "मोती नगर",
  "Moulsari Avenue": "मौलसरी एवेन्यू",
  "Mundka": "मुंडका",
  "Mundka Industrial Area": "मुंडका इंडस्ट्रियल एरिया",
  "Munirka": "मुनिरका",
  "Murad Nagar": "मुरादनगर",
  "N.H.P.C. Chowk": "एनएचपीसी चौक",
  "Najafgarh": "नजफगढ़",
  "Nanaksar - Sonia Vihar": "नानकसर - सोनिया विहार",
  "Nangli": "नंगली",
  "Nangloi": "नांगलोई",
  "Nangloi Railway Station": "नांगलोई रेलवे स्टेशन",
  "Naraina Vihar": "नारायणा विहार",
  "Nawada": "नवादा",
  "Neelam Chowk Ajronda": "नीलम चौक अजरौंदा",
  "Nehru Enclave": "नेहरू एन्क्लेव",
  "Nehru Place": "नेहरू प्लेस",
  "Netaji Subhash Place": "नेताजी सुभाष प्लेस",
  "New Ashok Nagar": "न्यू अशोक नगर",
  "New Delhi": "नई दिल्ली",
  "New Delhi Airport Express Terminal": "नई दिल्ली",
  "Nirman Vihar": "निर्माण विहार",
  "Noida City Centre": "नोएडा सिटी सेंटर",
  "Noida Electronic City": "नोएडा इलेक्ट्रॉनिक सिटी",
  "Noida Golf Course": "गोल्फ कोर्स",
  "Noida Sector 101": "नोएडा सेक्टर 101",
  "Noida Sector 137": "नोएडा सेक्टर 137",
  "Noida Sector 142": "नोएडा सेक्टर 142",
  "Noida Sector 143": "नोएडा सेक्टर 143",
  "Noida Sector 144": "नोएडा सेक्टर 144",
  "Noida Sector 145": "नोएडा सेक्टर 145",
  "Noida Sector 146": "नोएडा सेक्टर 146",
  "Noida Sector 147": "नोएडा सेक्टर 147",
  "Noida Sector 148": "नोएडा सेक्टर 148",
  "Noida Sector 15": "नोएडा सेक्टर-15",
  "Noida Sector 16": "नोएडा सेक्टर-16",
  "Noida Sector 18": "नोएडा सेक्टर-18",
  "Noida Sector 34": "नोएडा सेक्टर-34",
  "Noida Sector 51": "नोएडा सेक्टर 51",
  "Noida Sector 52": "नोएडा सेक्टर-52",
  "Noida Sector 59": "नोएडा सेक्टर-59",
  "Noida Sector 61": "नोएडा सेक्टर-61",
  "Noida Sector 62": "नोएडा सेक्टर-62",
  "Noida Sector 76": "नोएडा सेक्टर 76",
  "Noida Sector 81": "नोएडा सेक्टर 81",
  "Noida Sector 83": "नोएडा सेक्टर 83",
  "North Pitampura - Prashant Vihar": "नॉर्थ पीतमपुरा - प्रशांत विहार",
  "NSEZ": "एनएसईज़ेड",
  "Okhla Bird Sanctuary": "ओखला बर्ड सैंक्चुअरी",
  "Okhla NSIC": "ओखला एनएसआईसी",
  "Okhla Vihar": "ओखला विहार",
  "Old Faridabad": "ओल्ड फरीदाबाद",
  "Palam": "पालम",
  "Panchsheel Park": "पंचशील पार्क",
  "Pandit Shree Ram Sharma": "पंडित श्री राम शर्मा",
  "Pari Chowk": "परी चौक",
  "Paschim Vihar East": "पश्चिम विहार पूर्व",
  "Paschim Vihar West": "पश्चिम विहार पश्चिम",
  "Patel Chowk": "पटेल चौक",
  "Patel Nagar": "पटेल नगर",
  "Peeragarhi": "पीरागढ़ी",
  "Phase 3": "डीएलएफ़ फ़ेज़ 3",
  "Pratap Nagar": "प्रताप नगर",
  "Preet Vihar": "प्रीत विहार",
  "Pul Bangash": "पुलबंगश",
  "Punjabi Bagh": "पंजाबी बाग़",
  "Punjabi Bagh West": "पंजाबी बाग पश्चिम",
  "Qutab Minar": "क़ुतुब मीनार",
  "R. K. Puram": "आर के पुरम",
  "Rainbow Metro Station": "रेनबो",
  "Raj Bagh": "राज बाग़",
  "Raja Nahar Singh": "राजा नाहर सिंह (बल्लभगढ़)",
  "Rajdhani Park": "राजधानी पार्क",
  "Rajendra Nagar": "मेजर मोहित शर्मा राजेन्द्र नगर",
  "Rajendra Place": "राजेंद्र प्लेस",
  "Rajiv Chowk": "राजीव चौक",
  "Rajouri Garden": "राजौरी गार्डन",
  "Ramakrishna Ashram Marg": "रामकृष्ण आश्रम मार्ग",
  "Ramesh Nagar": "रमेश नगर",
  "Rithala": "रिठाला",
  "Rohini East": "रोहिणी ईस्ट",
  "Rohini Sector 18, 19": "रोहिणी सेक्टर - 18,19",
  "Rohini West": "रोहिणी वेस्ट",
  "Sadar Bazar Cantonment": "सदर बाजार छावनी",
  "Sahibabad": "साहिबाबाद",
  "Saket": "साकेत",
  "Samaypur Badli": "समयपुर बादली",
  "Sant Surdas (Sihi)": "संत सूरदास (सिही)",
  "Sarai": "सराय",
  "Sarai Kale Khan": "सराय काले खां",
  "Sarai Kale Khan - Nizamuddin": "सराय काले खान निज़ामुद्दीन",
  "Sarita Vihar": "सरिता विहार",
  "Sarojini Nagar": "सरोजिनी नगर",
  "Satguru Ramsingh Marg": "सतगुरु राम सिंह मार्ग",
  "Sector 28": "सेक्टर-28",
  "Sector 42-43": "सेक्टर 42-43",
  "Sector 53-54": "सेक्टर 53-54",
  "Sector 54 Chowk": "सेक्टर 54 चौक",
  "Sector 55–56": "सेक्टर 55-56",
  "Seelampur": "सीलमपुर",
  "Seva Teerth": "सेवा तीर्थ",
  "Shadipur": "शादीपुर",
  "Shahdara": "शाहदरा",
  "Shaheed Nagar": "शहीद नगर",
  "Shaheed Sthal": "शहीद स्थल (न्यू बस अड्डा)",
  "Shakurpur": "शकूरपुर",
  "Shalimar Bagh": "शालीमार बाग",
  "Shankar Vihar": "शंकर विहार",
  "Shastri Nagar": "शास्त्री नगर",
  "Shastri Park": "शास्त्री पार्क",
  "Shatabdi Nagar": "शताब्दी नगर",
  "Shiv Vihar": "शिव विहार",
  "Shivaji Park": "शिवाजी पार्क",
  "Shivaji Stadium": "शिवाजी स्टेडियम",
  "Shree Ram Mandir Mayur Vihar": "श्री राम मंदिर मयूर विहार",
  "Shyam Park": "श्याम पार्क",
  "Sikanderpur": "सिकंदरपुर",
  "Sir M. Vishweshwaraiah Moti Bagh": "सर म. विश्वेश्वरैया मोती बाग",
  "Soorghat": "सोरघाट",
  "South Extension": "साउथ एक्सटेंशन",
  "Subhash Nagar": "सुभाष नगर",
  "Sukhdev Vihar": "सुखदेव विहार",
  "Sultanpur": "सुल्तानपुर",
  "Supreme Court": "सुप्रीम कोर्ट",
  "Surajmal Stadium": "महाराजा सूरजमल स्टेडियम",
  "Tagore Garden": "टैगोर गार्डन",
  "Terminal 1 IGI Airport": "टर्मिनल-1 आईजीआई हवाई अड्डा",
  "Tikri Border": "टिकरी बॉर्डर",
  "Tikri Kalan": "टिकरी कलाँ",
  "Tilak Nagar": "तिलक नगर",
  "Tis Hazari": "तीस हज़ारी",
  "Trilokpuri Sanjay Lake": "त्रिलोकपुरी-संजय झील",
  "Tughlakabad": "तुगलकाबाद स्टेशन",
  "Udyog Nagar": "उद्योग नगर",
  "Uttam Nagar East": "उत्तम नगर ईस्ट",
  "Uttam Nagar West": "उत्तम नगर वेस्ट",
  "Vaishali": "वैशाली",
  "Vasant Vihar": "वसंत विहार",
  "Vidhan Sabha": "विधान सभा",
  "Vinobapuri": "विनोबापुरी",
  "Vishwa Vidyalaya": "विश्वविद्यालय",
  "Welcome": "वेलकम",
  "Yamuna Bank": "यमुना बैंक",
  "Yamuna Vihar": "यमुना विहार",
  "Yashobhoomi Dwarka Sector 25": "यशोभूमि द्वारका सेक्टर - 25",
};
// English display names where OSM's are awkward.
const ENGLISH: Record<string, string> = {
  'A.I.I.M.S.': 'AIIMS',
  'N.H.P.C. Chowk': 'NHPC Chowk',
  'New Delhi Airport Express Terminal': 'New Delhi',
  'Phase 3': 'DLF Phase 3',
  'Rainbow Metro Station': 'Rainbow',
  'Moulsari Avenue': 'Moulsari Avenue',
  'Depot': 'Depot',
  'Badarpur': 'Badarpur Border',
  'Dwarka - Kakrola': 'Dwarka',
  'M G Road': 'MG Road',
  'Mayur Vihar - I': 'Mayur Vihar-I',
  'Nangloi Railway Station': 'Nangloi Railway Station',
  'Rajendra Nagar': 'Major Mohit Sharma Rajendra Nagar',
  'Vishwa Vidyalaya': 'Vishwavidyalaya',
};

// Station sequences for through services OSM keeps in separate relations, and for the Pink Line ring.
const BLUE_VAISHALI = [
  'Dwarka Sector 21', 'Dwarka Sector 8', 'Dwarka Sector 9', 'Dwarka Sector 10', 'Dwarka Sector 11', 'Dwarka Sector 12',
  'Dwarka Sector 13', 'Dwarka Sector 14', 'Dwarka - Kakrola', 'Dwarka Mor', 'Nawada', 'Uttam Nagar West', 'Uttam Nagar East',
  'Janakpuri West', 'Janakpuri East', 'Tilak Nagar', 'Subhash Nagar', 'Tagore Garden', 'Rajouri Garden', 'Ramesh Nagar',
  'Moti Nagar', 'Kirti Nagar', 'Shadipur', 'Patel Nagar', 'Rajendra Place', 'Karol Bagh', 'Jhandewalan',
  'Ramakrishna Ashram Marg', 'Rajiv Chowk', 'Barakhambha Road', 'Mandi House', 'Supreme Court', 'Indraprastha',
  'Yamuna Bank', 'Laxmi Nagar', 'Nirman Vihar', 'Preet Vihar', 'Karkarduma', 'Anand Vihar', 'Kaushambi', 'Vaishali',
];
const GREEN_KIRTI_NAGAR = [
  'Kirti Nagar', 'Satguru Ramsingh Marg', 'Ashok Park Main', 'Punjabi Bagh', 'Punjabi Bagh West', 'Shivaji Park', 'Madipur',
  'Paschim Vihar East', 'Paschim Vihar West', 'Peeragarhi', 'Udyog Nagar', 'Surajmal Stadium', 'Nangloi',
  'Nangloi Railway Station', 'Rajdhani Park', 'Mundka', 'Mundka Industrial Area', 'Ghevra', 'Tikri Kalan', 'Tikri Border',
  'Pandit Shree Ram Sharma', 'Bahadurgarh City', 'Brigadier Hoshiyar Singh',
];
const PINK_RING = [
  'Majlis Park', 'Azadpur', 'Shalimar Bagh', 'Netaji Subhash Place', 'Shakurpur', 'Punjabi Bagh West', 'ESI - Basaidarapur',
  'Rajouri Garden', 'Mayapuri', 'Naraina Vihar', 'Delhi Cantt', 'Durgabai Deshmukh South Campus',
  'Sir M. Vishweshwaraiah Moti Bagh', 'Bhikaji Cama Place', 'Sarojini Nagar', 'Dilli Haat - INA', 'South Extension',
  'Lajpat Nagar', 'Vinobapuri', 'Ashram', 'Sarai Kale Khan - Nizamuddin', 'Mayur Vihar - I', 'Shree Ram Mandir Mayur Vihar',
  'Trilokpuri Sanjay Lake', 'East Vinod Nagar - Mayur Vihar - II', 'Mandawali - West Vinod Nagar', 'IP Extension',
  'Anand Vihar', 'Karkarduma', 'Karkarduma Court', 'Krishna Nagar', 'East Azad Nagar', 'Welcome', 'Jaffrabad',
  'Maujpur-Babarpur', 'Yamuna Vihar', 'Bhajanpura', 'Khajuri Khas', 'Nanaksar - Sonia Vihar', 'Soorghat',
  'Jagatpur - Wazirabad', 'Jharoda Majra', 'Burari', 'Majlis Park',
];

const lines: SimLineConfig[] = [
  {
    id: 'red', system: 'dmrc', name: 'Red Line', nameLocal: 'रेड लाइन', short: '1', color: '#ED1C24', bullet: 'circle', kind: 'metro',
    osm: { relations: [447214, 8037718] },
    run: { ...METRO, trip: { from: 'Rithala', to: 'Shaheed Sthal', minutes: 68 } },
    // Every other train turns back at Dilshad Garden.
    service: dmrc(['7:00', '7:40', '10:30'], ['8:20', '9:00', '10:30'], '06:00', '23:00', { 'Dilshad Garden': { first: '05:45', last: '23:16' } }),
    patterns: [
      { from: 'Rithala', to: 'Shaheed Sthal', share: 1 },
      { from: 'Rithala', to: 'Dilshad Garden', share: 1 },
    ],
    stock: [{ stock: 'delhi-rs1', cars: 8 }],
    directions: ['Eastbound', 'Westbound'],
  },
  {
    id: 'yellow', system: 'dmrc', name: 'Yellow Line', nameLocal: 'येलो लाइन', short: '2', color: '#FFCB05', bullet: 'circle', kind: 'metro',
    osm: { relations: [447210, 8037712] },
    run: { ...METRO, trip: { from: 'Samaypur Badli', to: 'Millennium City Centre Gurugram', minutes: 86 } },
    // Every other train starts at Vishwavidyalaya.
    service: dmrc(['5:48', '6:10', '8:00'], ['7:00', '7:10', '8:00'], '06:00', '23:00', { 'Vishwa Vidyalaya': { first: '05:30', last: '23:17' } }),
    patterns: [
      { from: 'Samaypur Badli', to: 'Millennium City Centre Gurugram', share: 1 },
      { from: 'Vishwa Vidyalaya', to: 'Millennium City Centre Gurugram', share: 1 },
    ],
    stock: [{ stock: 'delhi-movia', share: 0.6, cars: 8 }, { stock: 'delhi-rs1', share: 0.4, cars: 8 }],
    directions: ['Southbound', 'Northbound'],
  },
  {
    // Trains alternate between the Noida and Vaishali branches; a third of them turn back at Dwarka.
    id: 'blue', system: 'dmrc', name: 'Blue Line', nameLocal: 'ब्लू लाइन', short: '3', color: '#0072BC', bullet: 'circle', kind: 'metro',
    osm: { relations: [8037669, 447209, 8037670, 2535795], sequences: [BLUE_VAISHALI] },
    run: { ...METRO, trip: { from: 'Rajiv Chowk', to: 'Noida Electronic City', minutes: 46 } },
    service: dmrc(['5:42', '6:30', '9:00'], ['7:00', '7:00', '9:00'], '06:00', '23:00', {
      'Dwarka Sector 21': { last: '22:50' },
      'Noida Electronic City': { last: '22:24' },
      Vaishali: { last: '22:45' },
    }),
    patterns: [
      { from: 'Dwarka Sector 21', to: 'Noida Electronic City', share: 2 / 3 },
      { from: 'Dwarka Sector 21', to: 'Vaishali', via: ['Laxmi Nagar'], share: 2 / 3 },
      { from: 'Dwarka - Kakrola', to: 'Noida Electronic City', share: 1 / 3 },
      { from: 'Dwarka - Kakrola', to: 'Vaishali', via: ['Laxmi Nagar'], share: 1 / 3 },
    ],
    stock: [{ stock: 'delhi-movia', share: 0.6, cars: 8 }, { stock: 'delhi-rs1', share: 0.4, cars: 8 }],
    directions: ['Eastbound', 'Westbound'],
  },
  {
    // Kirti Nagar and Inderlok trains alternate to Ashok Park Main; a third of Inderlok trains run beyond Mundka.
    id: 'green', system: 'dmrc', name: 'Green Line', nameLocal: 'ग्रीन लाइन', short: '5', color: '#22B24C', bullet: 'circle', kind: 'metro',
    osm: { relations: [8037666, 8037687, 2535796, 8037675], sequences: [GREEN_KIRTI_NAGAR] },
    run: { ...METRO, trip: { from: 'Brigadier Hoshiyar Singh', to: 'Inderlok', minutes: 42 } },
    service: dmrc(['8:20', '10:00', '11:20'], ['10:20', '10:20', '11:20'], '06:00', '23:00', { 'Brigadier Hoshiyar Singh': { first: '06:13', last: '22:45' } }),
    patterns: [
      { from: 'Kirti Nagar', to: 'Brigadier Hoshiyar Singh', share: 1 },
      { from: 'Inderlok', to: 'Brigadier Hoshiyar Singh', share: 1 / 3 },
      { from: 'Inderlok', to: 'Mundka', share: 2 / 3 },
    ],
    stock: [{ stock: 'delhi-rs-sg-green', cars: 4 }],
    directions: ['Westbound', 'Eastbound'],
  },
  {
    // Every other train turns back at Badarpur Border.
    id: 'violet', system: 'dmrc', name: 'Violet Line', nameLocal: 'वायलेट लाइन', short: '6', color: '#702C91', bullet: 'circle', kind: 'metro',
    osm: { relations: [2535797, 8037705] },
    run: { ...METRO, trip: { from: 'Central Secretariat', to: 'Raja Nahar Singh', minutes: 65 } },
    service: dmrc(['6:48', '8:00', '10:20'], ['9:20', '10:32', '10:20'], '06:00', '23:00', { 'Raja Nahar Singh': { last: '22:20' } }),
    patterns: [
      { from: 'Kashmere Gate', to: 'Raja Nahar Singh', share: 1 },
      { from: 'Kashmere Gate', to: 'Badarpur', share: 1 },
    ],
    stock: [{ stock: 'delhi-rs-sg-violet', cars: 6 }],
    directions: ['Southbound', 'Northbound'],
  },
  {
    id: 'airport', system: 'dmrc', name: 'Airport Express Line', nameLocal: 'एयरपोर्ट एक्सप्रेस लाइन', short: 'AE', color: '#EB8923', bullet: 'circle', kind: 'metro',
    osm: { relations: [2535798, 8037715] },
    run: { vmax: 120, acc: 0.9, dec: 1.0, dwell: 40, trip: { from: 'New Delhi Airport Express Terminal', to: 'Yashobhoomi Dwarka Sector 25', minutes: 22 } },
    service: flat(10, '05:00', '23:40', { 'Yashobhoomi Dwarka Sector 25': { first: '04:40', last: '23:15' } }),
    patterns: [{ from: 'New Delhi Airport Express Terminal', to: 'Yashobhoomi Dwarka Sector 25', share: 1 }],
    stock: [{ stock: 'delhi-caf-airport', cars: 6 }],
    directions: ['To the airport', 'To New Delhi'],
  },
  {
    // Since March 2026 a ring in both directions, plus a Maujpur–Shiv Vihar shuttle.
    id: 'pink', system: 'dmrc', name: 'Pink Line', nameLocal: 'पिंक लाइन', short: '7', color: '#F172AC', bullet: 'circle', kind: 'metro',
    osm: { relations: [8242437, 8241298], sequences: [PINK_RING] },
    run: { ...METRO, trip: { from: 'Azadpur', to: 'Welcome', minutes: 89 } },
    service: dmrc(['5:26', '6:40', '7:57'], ['6:28', '6:40', '7:57'], '06:00', '22:30'),
    groups: { spur: flat(mmss('8:10'), '06:00', '23:00', { 'Shiv Vihar': { last: '22:50' } }) },
    patterns: [
      { from: 'Majlis Park', to: 'Majlis Park', loop: true, share: 1 },
      { from: 'Maujpur-Babarpur', to: 'Shiv Vihar', share: 1, group: 'spur' },
    ],
    stock: [{ stock: 'delhi-rotem-uto', share: 0.75, cars: 6 }, { stock: 'delhi-metropolis', share: 0.25, cars: 6 }],
  },
  {
    // Every other Botanical Garden train continues to Krishna Park Extension; the Majlis Park–Deepali Chowk section is separate.
    id: 'magenta', system: 'dmrc', name: 'Magenta Line', nameLocal: 'मैजेंटा लाइन', short: '8', color: '#C6168D', bullet: 'circle', kind: 'metro',
    osm: { relations: [8385429, 8385430, 20300114, 20300115] },
    run: { ...METRO, trip: { from: 'Botanical Garden', to: 'Janakpuri West', minutes: 59 } },
    service: dmrc(['10:40', '11:36', '12:50'], ['12:10', '13:24', '12:50'], '06:00', '23:00', {
      'Krishna Park Extension': { first: '05:50', last: '22:50' },
      'Botanical Garden': { last: '23:17' },
    }),
    groups: { north: dmrc(['5:20', '5:20', '5:20'], ['6:20', '6:20', '6:20'], '06:00', '23:00', { 'Deepali Chowk': { first: '06:30' } }) },
    patterns: [
      { from: 'Botanical Garden', to: 'Janakpuri West', share: 1 },
      { from: 'Botanical Garden', to: 'Krishna Park Extension', share: 1 },
      // Only Alstom's new Metropolis trains run the northern section, from Mukundpur depot.
      { from: 'Majlis Park', to: 'Deepali Chowk', share: 1, group: 'north', stock: [{ stock: 'delhi-metropolis', cars: 6 }] },
    ],
    stock: [{ stock: 'delhi-rotem-uto', cars: 6 }],
    directions: ['Westbound', 'Eastbound'],
  },
  {
    id: 'grey', system: 'dmrc', name: 'Grey Line', nameLocal: 'ग्रे लाइन', short: '9', color: '#939598', bullet: 'circle', kind: 'metro',
    osm: { relations: [3537978, 8051592] },
    run: { ...METRO, trip: { from: 'Dwarka - Kakrola', to: 'Dhansa Bus Stand', minutes: 9 } },
    service: dmrc(['7:30', '7:30', '12:00'], ['12:00', '12:00', '12:00']),
    patterns: [{ from: 'Dwarka - Kakrola', to: 'Dhansa Bus Stand', share: 1 }],
    stock: [{ stock: 'delhi-rotem-uto', cars: 6 }],
    directions: ['Westbound', 'Eastbound'],
  },
  {
    // Out through the one-way loop around DLF Cyber City and back, as in DMRC's own timetable.
    id: 'rapid', system: 'dmrc', name: 'Rapid Metro Gurugram', nameLocal: 'रैपिड मेट्रो गुरुग्राम', short: 'RM', color: '#16C1F3', bullet: 'circle', kind: 'metro',
    osm: { relations: [4481323, 7890002] },
    run: { vmax: 70, acc: 0.9, dec: 1.0, dwell: 25, trip: { from: 'Sector 55–56', to: 'Sikanderpur', minutes: 10 } },
    service: {
      weekday: { first: '06:00', last: '22:00', headways: [['06:00', 6], ['08:00', 4.8], ['11:00', 6], ['17:00', 4.8], ['20:30', 6]] },
      saturday: { first: '06:00', last: '22:00', headways: [['06:00', 6]] },
      sunday: { first: '06:00', last: '22:00', headways: [['06:00', 7]] },
    },
    patterns: [{ from: 'Sector 55–56', to: 'Phase 3', via: ['Cyber City'], share: 1 }],
    stock: [{ stock: 'delhi-rapid-metro', cars: 3 }],
  },
  {
    id: 'aqua', system: 'nmrc', name: 'Aqua Line', nameLocal: 'एक्वा लाइन', short: 'AQ', color: '#00B7C3', bullet: 'circle', kind: 'metro',
    osm: { relations: [9268568, 9268569] },
    run: { ...METRO, trip: { from: 'Noida Sector 51', to: 'Depot', minutes: 45 } },
    service: {
      weekday: { first: '06:00', last: '22:00', headways: [['06:00', 10], ['08:00', 7.5], ['11:00', 10], ['17:00', 7.5], ['20:30', 10]] },
      saturday: { first: '06:00', last: '22:00', headways: [['06:00', 10]] },
      sunday: { first: '06:00', last: '22:00', headways: [['06:00', 15]] },
    },
    patterns: [{ from: 'Noida Sector 51', to: 'Depot', share: 1 }],
    stock: [{ stock: 'delhi-nmrc-aqua', cars: 4 }],
    directions: ['Southbound', 'Northbound'],
  },
  {
    id: 'namo', system: 'ncrtc', name: 'Namo Bharat (Delhi–Meerut RRTS)', nameLocal: 'नमो भारत', short: 'NB', color: '#F0631E', bullet: 'pill', kind: 'rail',
    osm: { relations: [17337287, 17337288] },
    run: { vmax: 160, acc: 0.9, dec: 1.0, dwell: 45, trip: { from: 'Sarai Kale Khan', to: 'Modipuram', minutes: 62 } },
    service: {
      weekday: { first: '06:00', last: '22:00', headways: [['06:00', 15], ['08:00', 10], ['11:00', 15], ['17:00', 10], ['20:30', 15]] },
      saturday: { first: '06:00', last: '22:00', headways: [['06:00', 15]] },
      sunday: { first: '06:00', last: '22:00', headways: [['06:00', 15]] },
    },
    patterns: [{ from: 'Sarai Kale Khan', to: 'Modipuram', share: 1 }],
    stock: [{ stock: 'delhi-namo-bharat', cars: 6 }],
    directions: ['To Meerut', 'To Delhi'],
  },
];

const rename: Record<string, [string, string]> = {};
for (const [en, hi] of Object.entries(HINDI)) rename[en] = [ENGLISH[en] ?? en, hi];
for (const [osm, en] of Object.entries(ENGLISH)) if (!rename[osm]) console.warn(`  no Hindi name for ${osm}`);

await buildSimCity({
  city: 'delhi',
  systems: [
    { id: 'dmrc', name: 'Delhi Metro' },
    { id: 'nmrc', name: 'Noida Metro' },
    { id: 'ncrtc', name: 'Namo Bharat' },
  ],
  lines,
  stations: { rename },
  names: { local: ['name'], en: ['name:en', 'name'] },
  // Gazetted holidays run the Sunday service (lunar dates are approximate).
  calendar: {
    holidays: [
      '2026-01-26', '2026-03-04', '2026-03-21', '2026-04-03', '2026-05-27', '2026-08-15', '2026-10-02', '2026-10-20',
      '2026-11-08', '2026-11-24', '2026-12-25',
      '2027-01-26', '2027-03-10', '2027-03-22', '2027-03-26', '2027-05-17', '2027-08-15', '2027-10-02', '2027-10-09',
      '2027-10-29', '2027-11-14', '2027-12-25',
    ],
  },
  attribution: ['Service: DMRC published train frequencies (simulated)', 'Hindi station names: DMRC'],
});
